Repository woowacourse-teams/2023-hang-log, pull requests merged in 2023-07, with the labels that each got.

#2 chore: Backend 프로젝트 초기 세팅
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/hanglog/HangLogApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/hanglog/HangLogApplicationTests.java
Labels: 🌏 Environment, BE

#4 Trip 도메인 구조 설계 및 엔티티 클래스 작성
  backend/src/main/java/hanglog/HangLogApplication.java
  backend/src/main/java/hanglog/category/Category.java
  backend/src/main/java/hanglog/category/repository/CategoryRepository.java
  backend/src/main/java/hanglog/expense/Expense.java
  backend/src/main/java/hanglog/expense/repository/ExpenseRepository.java
  backend/src/main/java/hanglog/global/BaseEntity.java
  backend/src/main/java/hanglog/global/type/StatusType.java
  backend/src/main/java/hanglog/image/domain/Image.java
  backend/src/main/java/hanglog/image/domain/repository/ImageRepository.java
  backend/src/main/java/hanglog/trip/domain/City.java
  backend/src/main/java/hanglog/trip/domain/DayLog.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/domain/Place.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/domain/TripCity.java
  backend/src/main/java/hanglog/trip/domain/repository/CityRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/DayLogRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/ItemRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/PlaceRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/TripCityRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/TripRepository.java
  backend/src/main/java/hanglog/trip/domain/type/ItemType.java
  backend/src/main/resources/application.properties
Labels: ✨ Feature, BE

#13 Trip 생성 API 구현
  backend/build.gradle
  backend/src/main/java/hanglog/global/BaseEntity.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/presentation/TripController.java
  backend/src/main/java/hanglog/trip/presentation/dto/request/TripRequest.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/main/resources/application.properties
  backend/src/test/java/hanglog/trip/fixture/TripFixture.java
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: ✨ Feature, BE

#18 Revert "Trip 생성 API 구현"
  backend/build.gradle
  backend/src/main/java/hanglog/global/BaseEntity.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/presentation/TripController.java
  backend/src/main/java/hanglog/trip/presentation/dto/request/TripRequest.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/main/resources/application.properties
  backend/src/test/java/hanglog/trip/fixture/TripFixture.java
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: 🔨 Refactor, BE

#25 RestDocs 적용
  backend/build.gradle
  backend/src/docs/asciidoc/docs.adoc
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
  backend/src/test/java/hanglog/trip/restdocs/RestDocsConfiguration.java
  backend/src/test/java/hanglog/trip/restdocs/RestDocsTest.java
Labels: 🌏 Environment, BE

#29 페이지 path 상수화
  frontend/src/constants/path.ts
Labels: ✨ Feature, FE

#30 Header 컴포넌트 생성
  frontend/src/App.tsx
  frontend/src/assets/svg/logo-horizontal.svg
  frontend/src/components/layout/Header/Header.style.ts
  frontend/src/components/layout/Header/Header.tsx
Labels: ✨ Feature, FE

#31 axios 인스턴스 생성 및 endpoint 상수화
  frontend/src/api/axiosInstance.ts
  frontend/src/constants/api.ts
Labels: ✨ Feature, FE

#42 #16 Trip 수정 및 삭제 API 구현
  backend/src/main/java/hanglog/global/AdviceHandler.java
  backend/src/main/java/hanglog/global/BaseEntity.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/dto/request/TripCreateRequest.java
  backend/src/main/java/hanglog/trip/dto/request/TripUpdateRequest.java
  backend/src/main/java/hanglog/trip/presentation/TripController.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/test/java/hanglog/trip/fixture/TripFixture.java
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: ✨ Feature, BE

#21 Item 생성, 수정, 삭제 API 구현
  backend/src/main/java/hanglog/category/Category.java
  backend/src/main/java/hanglog/category/repository/CategoryRepository.java
  backend/src/main/java/hanglog/expense/Expense.java
  backend/src/main/java/hanglog/trip/domain/DayLog.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/domain/Place.java
  backend/src/main/java/hanglog/trip/domain/type/ItemType.java
  backend/src/main/java/hanglog/trip/presentation/ItemController.java
  backend/src/main/java/hanglog/trip/presentation/dto/request/ExpenseRequest.java
  backend/src/main/java/hanglog/trip/presentation/dto/request/ItemRequest.java
  backend/src/main/java/hanglog/trip/presentation/dto/request/PlaceRequest.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/trip/fixture/ExpenseFixture.java
  backend/src/test/java/hanglog/trip/fixture/ItemFixture.java
  backend/src/test/java/hanglog/trip/fixture/PlaceFixture.java
  backend/src/test/java/hanglog/trip/presentation/ItemControllerTest.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: ✨ Feature, BE

#43 DayLog 조회, 제목 수정 API 구현
  backend/src/docs/asciidoc/docs.adoc
  backend/src/main/java/hanglog/trip/domain/DayLog.java
  backend/src/main/java/hanglog/trip/presentation/DayLogController.java
  backend/src/main/java/hanglog/trip/presentation/dto/request/DayLogUpdateTitleRequest.java
  backend/src/main/java/hanglog/trip/presentation/dto/response/DayLogGetResponse.java
  backend/src/main/java/hanglog/trip/service/DayLogService.java
  backend/src/test/java/hanglog/trip/fixture/DayLogFixture.java
  backend/src/test/java/hanglog/trip/presentation/DayLogControllerTest.java
  backend/src/test/java/hanglog/trip/service/DayLogServiceTest.java
Labels: ✨ Feature, BE

#47 Place, Category 필드 및 Request DTO 변경
  backend/src/main/java/hanglog/category/Category.java
  backend/src/main/java/hanglog/category/repository/CategoryRepository.java
  backend/src/main/java/hanglog/trip/domain/Place.java
  backend/src/main/java/hanglog/trip/presentation/dto/request/PlaceRequest.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/trip/fixture/ExpenseFixture.java
  backend/src/test/java/hanglog/trip/fixture/PlaceFixture.java
  backend/src/test/java/hanglog/trip/presentation/ItemControllerTest.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: 🔨 Refactor, BE

#60 Category 필드 변경
  backend/src/main/java/hanglog/category/Category.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/trip/fixture/ExpenseFixture.java
  backend/src/test/java/hanglog/trip/fixture/PlaceFixture.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: 🔨 Refactor, BE

#57 DayLog 조회시 실제 날짜 추가
  backend/src/main/java/hanglog/trip/presentation/dto/response/DayLogGetResponse.java
  backend/src/test/java/hanglog/trip/fixture/DayLogFixture.java
  backend/src/test/java/hanglog/trip/presentation/DayLogControllerTest.java
  backend/src/test/java/hanglog/trip/service/DayLogServiceTest.java
Labels: ✨ Feature, BE

#63 전체 Item 조회 기능 구현
  backend/src/main/java/hanglog/category/Category.java
  backend/src/main/java/hanglog/category/CategoryResponse.java
  backend/src/main/java/hanglog/expense/Expense.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/domain/type/ItemType.java
  backend/src/main/java/hanglog/trip/dto/request/DayLogUpdateTitleRequest.java
  backend/src/main/java/hanglog/trip/dto/request/ExpenseRequest.java
  backend/src/main/java/hanglog/trip/dto/request/ItemRequest.java
  backend/src/main/java/hanglog/trip/dto/request/PlaceRequest.java
  backend/src/main/java/hanglog/trip/dto/response/DayLogGetResponse.java
  backend/src/main/java/hanglog/trip/dto/response/ExpenseResponse.java
  backend/src/main/java/hanglog/trip/dto/response/ItemResponse.java
  backend/src/main/java/hanglog/trip/dto/response/PlaceResponse.java
  backend/src/main/java/hanglog/trip/presentation/DayLogController.java
  backend/src/main/java/hanglog/trip/presentation/ItemController.java
  backend/src/main/java/hanglog/trip/service/DayLogService.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/trip/fixture/ExpenseFixture.java
  backend/src/test/java/hanglog/trip/fixture/ItemFixture.java
  backend/src/test/java/hanglog/trip/fixture/PlaceFixture.java
  backend/src/test/java/hanglog/trip/presentation/DayLogControllerTest.java
  backend/src/test/java/hanglog/trip/presentation/ItemControllerTest.java
  backend/src/test/java/hanglog/trip/service/DayLogServiceTest.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: ✨ Feature, BE

#66 ItemService 에러 수정
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: 🔨 Refactor, BE

#51 TripList 페이지 구현
  frontend/src/api/axiosInstance.ts
  frontend/src/api/trips/trips.ts
  frontend/src/assets/svg/TripsHeader.svg
  frontend/src/assets/svg/tutorial1.svg
  frontend/src/assets/svg/tutorial2.svg
  frontend/src/assets/svg/tutorial3.svg
  frontend/src/assets/svg/tutorial4.svg
  frontend/src/components/Trips/TripsHeader/TripsHeader.tsx
  frontend/src/components/Trips/TripsItem/TripsItem.style.ts
  frontend/src/components/Trips/TripsItem/TripsItem.tsx
  frontend/src/components/Trips/TripsItemList/TripsItemList.style.ts
  frontend/src/components/Trips/TripsItemList/TripsItemList.tsx
  frontend/src/components/Trips/TripsItemNone/TripsItemNone.style.ts
  frontend/src/components/Trips/TripsItemNone/TripsItemNone.tsx
  frontend/src/components/Trips/TutorialModal/TutorialModal.style.ts
  frontend/src/components/Trips/TutorialModal/TutorialModal.tsx
  frontend/src/components/layout/Header/Header.style.ts
  frontend/src/constants/order.ts
  frontend/src/hooks/trips/useGetTrips.ts
  frontend/src/mocks/data/trips.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/trips.ts
  frontend/src/pages/TripsPage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/types/trips.ts
  frontend/src/utils/common/sortByStartDate.ts
Labels: ✨ Feature, FE

#49 도시입력창 & 제안목록 컴포넌트 구현
  frontend/.storybook/main.ts
  frontend/src/api/city/getCities.ts
  frontend/src/assets/svg/close-icon.svg
  frontend/src/assets/svg/search-pin-icon.svg
  frontend/src/components/common/CitySearchBar/CitySearchBar.style.ts
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/components/common/CitySuggestion/CitySuggestion.style.ts
  frontend/src/components/common/CitySuggestion/CitySuggestion.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/path.ts
  frontend/src/constants/ui.ts
  frontend/src/hooks/common/useCitySuggestion.ts
  frontend/src/hooks/common/useCityTags.ts
  frontend/src/mocks/data/city.ts
  frontend/src/mocks/handlers/city.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/stories/common/CitySearchBar.stories.tsx
  frontend/src/utils/cityFilter.ts
Labels: ✨ Feature, FE

#67 DayLog 수정
  backend/src/main/java/hanglog/trip/domain/DayLog.java
  backend/src/main/java/hanglog/trip/dto/response/DayLogGetResponse.java
  backend/src/main/java/hanglog/trip/presentation/DayLogController.java
  backend/src/main/java/hanglog/trip/service/DayLogService.java
  backend/src/test/java/hanglog/trip/presentation/DayLogControllerTest.java
Labels: ✨ Feature, BE

#73 Item생성을 위한 DTO, Domain Validation 수정
  backend/src/main/java/hanglog/category/Category.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/domain/Place.java
  backend/src/main/java/hanglog/trip/dto/request/ExpenseRequest.java
  backend/src/main/java/hanglog/trip/dto/request/ItemRequest.java
  backend/src/main/java/hanglog/trip/dto/request/PlaceRequest.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/trip/fixture/ItemFixture.java
  backend/src/test/java/hanglog/trip/fixture/PlaceFixture.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: ✨ Feature, BE

#78 Item의 rating Size Validation 변경
  backend/src/main/java/hanglog/trip/dto/request/ItemRequest.java
Labels: 🔨 Refactor, BE

#80 TripController RestDocs 적용
  backend/src/docs/asciidoc/docs.adoc
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
Labels: 🔨 Refactor, BE

#83 front-end 코드 통합
  frontend/src/api/city/getCities.ts
  frontend/src/api/trips/trips.ts
  frontend/src/components/Trips/TripsHeader/TripsHeader.tsx
  frontend/src/components/Trips/TripsItem/TripsItem.style.ts
  frontend/src/components/Trips/TripsItem/TripsItem.tsx
  frontend/src/components/Trips/TripsItemList/TripsItemList.style.ts
  frontend/src/components/Trips/TripsItemList/TripsItemList.tsx
  frontend/src/components/Trips/TripsItemNone/TripsItemNone.style.ts
  frontend/src/components/Trips/TripsItemNone/TripsItemNone.tsx
  frontend/src/components/Trips/TutorialModal/TutorialModal.style.ts
  frontend/src/components/Trips/TutorialModal/TutorialModal.tsx
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/components/common/CitySuggestion/CitySuggestion.style.ts
  frontend/src/components/common/CitySuggestion/CitySuggestion.tsx
  frontend/src/components/layout/Header/Header.style.ts
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/hooks/api/useCityQuery.ts
  frontend/src/hooks/api/useDayLogOrderMutation.ts
  frontend/src/hooks/api/useGetTrips.ts
  frontend/src/hooks/api/useTripQuery.ts
  frontend/src/hooks/common/useCitySuggestion.ts
  frontend/src/hooks/common/useCityTags.ts
  frontend/src/mocks/data/city.ts
  frontend/src/mocks/data/trip.ts
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/pages/TripsPage/TripsPage.style.ts
  frontend/src/pages/TripsPage/TripsPage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/types/city.ts
  frontend/src/types/trip.ts
  frontend/src/types/tripItem.ts
  frontend/src/types/trips.ts
  frontend/src/utils/cityFilter.ts
  frontend/src/utils/sortByStartDate.ts
Labels: 🌏 Environment, 🔨 Refactor, FE

#87 도시입력창 & 제안목록 컴포넌트 수정
  frontend/src/assets/svg/search-pin-icon.svg
  frontend/src/components/common/CitySearchBar/CitySearchBar.style.ts
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/components/common/CitySuggestion/CitySuggestion.style.ts
  frontend/src/hooks/api/useCityQuery.ts
  frontend/src/hooks/common/useCitySuggestion.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#86 TripsHeader, TripsItemList, TripsItemListEmpty storybook 추가
  frontend/src/stories/common/TripsHeader.stories.tsx
  frontend/src/stories/common/TripsItemList.stories.tsx
  frontend/src/stories/common/TripsItemListEmpty.stories.tsx
Labels: ✨ Feature, FE

#88 TripItem 사진 정렬 버그 수정
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/mocks/handlers/dayLog.ts
Labels: 🐞 Bug, FE

#85 ItemController RestDocs 적용
  backend/src/docs/asciidoc/docs.adoc
  backend/src/test/java/hanglog/trip/presentation/ItemControllerTest.java
Labels: 🔨 Refactor, BE

#92 Trips 페이지 skeleton ui 추가
  frontend/src/components/Trips/TripsItem/TripsItem.style.ts
  frontend/src/components/Trips/TripsItem/TripsItemSkeleton.tsx
  frontend/src/components/Trips/TripsItemList/TripsItemListSkeleton.tsx
  frontend/src/pages/TripsPage/TripsPageSkeleton.tsx
  frontend/src/router/AppRouter.tsx
Labels: ✨ Feature, FE

#96 webpack dotenv 설정 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.config.js
Labels: 🌏 Environment, FE

#90 자동스크롤 기능 훅 분리
  frontend/src/components/common/CitySuggestion/CitySuggestion.tsx
  frontend/src/hooks/common/useAutoScroll.ts
  frontend/src/hooks/common/useCitySuggestion.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#95 날짜입력 컴포넌트 구현
  frontend/src/assets/svg/calendar-icon.svg
  frontend/src/components/common/DateInput/DateInput.style.ts
  frontend/src/components/common/DateInput/DateInput.tsx
  frontend/src/stories/common/DateInput.stories.tsx
  frontend/src/types/trips.ts
  frontend/src/utils/formatter.ts
Labels: ✨ Feature, FE

#94 Trip 목록 조회 기능 구현
  backend/src/main/java/hanglog/trip/domain/DayLog.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/dto/response/TripResponse.java
  backend/src/main/java/hanglog/trip/presentation/TripController.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/test/java/hanglog/trip/fixture/DayLogFixture.java
  backend/src/test/java/hanglog/trip/fixture/TripFixture.java
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
  backend/src/test/java/hanglog/trip/service/DayLogServiceTest.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: ✨ Feature, BE

#101 Item과 관련된 필드 수정
  backend/src/main/java/hanglog/expense/Expense.java
  backend/src/main/java/hanglog/image/domain/Image.java
  backend/src/main/java/hanglog/image/domain/repository/ImageRepository.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/dto/request/ExpenseRequest.java
  backend/src/main/java/hanglog/trip/dto/request/ItemRequest.java
  backend/src/main/java/hanglog/trip/dto/request/PlaceRequest.java
  backend/src/main/java/hanglog/trip/dto/response/ExpenseResponse.java
  backend/src/main/java/hanglog/trip/dto/response/ItemResponse.java
  backend/src/main/java/hanglog/trip/presentation/ItemController.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/trip/fixture/ExpenseFixture.java
  backend/src/test/java/hanglog/trip/presentation/ItemControllerTest.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: 🔨 Refactor, BE

#62 예외 처리 로직 구현
  backend/src/main/java/hanglog/global/AdviceHandler.java
  backend/src/main/java/hanglog/global/exception/BadRequestException.java
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/main/java/hanglog/global/exception/ExceptionResponse.java
  backend/src/main/java/hanglog/global/exception/GlobalExceptionHandler.java
Labels: ✨ Feature, BE

#98 feat: CORS 설정 Config 적용
  backend/src/main/java/hanglog/config/CorsConfig.java
Labels: ✨ Feature, BE

#102 도시제안목록에서 마우스 이동시 자동스크롤되는 기능 제거
  frontend/src/components/common/CitySuggestion/CitySuggestion.tsx
  frontend/src/hooks/common/useCitySuggestion.ts
Labels: 🔨 Refactor, FE

#99 TripItem 추가 모달 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/expense/getExpenseCategory.ts
  frontend/src/api/tripItem/postTripItem.ts
  frontend/src/components/common/DayLogItem/DayLogItem.tsx
  frontend/src/components/common/DayLogList/DayLogList.tsx
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.style.ts
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemCategoryInput/TripItemCategoryInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemDateInput/TripItemDateInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemExpenseInput/TripItemExpenseInput.style.ts
  frontend/src/components/trip/TripItemAddModal/TripItemExpenseInput/TripItemExpenseInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemMemoInput/TripItemMemoInput.style.ts
  frontend/src/components/trip/TripItemAddModal/TripItemMemoInput/TripItemMemoInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemStarRatingInput/TripItemStarRatingInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemTitleInput/TripItemTitleInput.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/trip.ts
  frontend/src/hooks/api/useAddTripItemMutation.ts
  frontend/src/hooks/api/useCityQuery.ts
  frontend/src/hooks/api/useExpenseCategoryQuery.ts
  frontend/src/hooks/api/useGetTrips.ts
  frontend/src/hooks/useAddTripItemForm.ts
  frontend/src/hooks/useTripItemExpenseInput.ts
  frontend/src/mocks/data/expense.ts
  frontend/src/mocks/data/trip.ts
  frontend/src/mocks/data/trips.ts
  frontend/src/mocks/handlers/expense.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/trip.ts
  frontend/src/mocks/handlers/tripItem.ts
  frontend/src/mocks/handlers/trips.ts
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/stories/common/DayLogList.stories.tsx
  frontend/src/stories/common/TripsItemList.stories.tsx
  frontend/src/types/expense.ts
  frontend/src/types/tripItem.ts
  frontend/src/utils/formatter.ts
  frontend/src/utils/validator.ts
  frontend/tsconfig.json
Labels: ✨ Feature, FE

#100 새로운 여행 생성 페이지 구현
  frontend/src/api/trips/newTrip.ts
  frontend/src/assets/svg/calendar-icon.svg
  frontend/src/assets/svg/create-page-image.svg
  frontend/src/components/Trips/TripsItem/TripsItem.style.ts
  frontend/src/components/Trips/TripsItem/TripsItem.tsx
  frontend/src/components/common/CitySearchBar/CitySearchBar.style.ts
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/components/common/DateInput/DateInput.style.ts
  frontend/src/components/common/DateInput/DateInput.tsx
  frontend/src/components/newTrip/NewTripForm/NewTripForm.style.ts
  frontend/src/components/newTrip/NewTripForm/NewTripForm.tsx
  frontend/src/hooks/api/useCityQuery.ts
  frontend/src/hooks/api/useNewTripMutation.ts
  frontend/src/hooks/api/useTripsQuery.ts
  frontend/src/hooks/common/useCitySuggestion.ts
  frontend/src/hooks/common/useCityTags.ts
  frontend/src/hooks/newTrip/useNewTripForm.ts
  frontend/src/mocks/handlers/trips.ts
  frontend/src/pages/TripCreatePage/TripCreatePage.style.ts
  frontend/src/pages/TripCreatePage/TripCreatePage.tsx
  frontend/src/pages/TripsPage/TripsPage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/types/trips.ts
Labels: ✨ Feature, FE

#109 Local MySQL 환경설정 구축
  backend/.gitignore
  backend/build.gradle
  backend/docker/docker-compose.yml
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
Labels: 🌏 Environment, BE

#112 Local MySQL 환경설정 버그 수정
  backend/src/main/resources/application.yml
Labels: 🐞 Bug, 🌏 Environment, BE

#113 RestDocs 수정
  backend/src/docs/asciidoc/docs.adoc
  backend/src/main/java/hanglog/category/Category.java
  backend/src/main/java/hanglog/expense/Expense.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/domain/Place.java
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
Labels: ✨ Feature, BE

#105 모든 city 조회 구현
  backend/.gitignore
  backend/src/docs/asciidoc/docs.adoc
  backend/src/main/java/hanglog/trip/dto/response/CityResponse.java
  backend/src/main/java/hanglog/trip/presentation/CityController.java
  backend/src/main/java/hanglog/trip/service/CityService.java
  backend/src/test/java/hanglog/trip/presentation/CityControllerTest.java
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
  backend/src/test/java/hanglog/trip/service/CityServiceTest.java
Labels: ✨ Feature, BE

#122 ErrorBoundary 컴포넌트 구현
  frontend/src/App.tsx
  frontend/src/api/HTTPError.ts
  frontend/src/api/axiosInstance.ts
  frontend/src/assets/svg/error-image.svg
  frontend/src/components/common/Error/Error.style.ts
  frontend/src/components/common/Error/Error.tsx
  frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/common/useResetError.ts
  frontend/src/pages/NotFoundPage/NotFoundPage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/utils/typeGuard.ts
Labels: ✨ Feature, FE

#123 dev/prod모드별 fetch 엔드포인트 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/constants/api.ts
  frontend/webpack.config.js
Labels: 🌏 Environment, FE

#119 예외 처리 상수 코드로 변경
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/main/java/hanglog/global/exception/InvalidDomainException.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/dto/request/ItemRequest.java
  backend/src/main/java/hanglog/trip/service/DayLogService.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: 🔨 Refactor, BE

#125 TripItem 추가 시 장소 자동 검색 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/tripItem/postTripItem.ts
  frontend/src/components/common/GoogleMapWrapper/GoogleMapWrapper.tsx
  frontend/src/components/trip/TripItemAddModal/CategoryInput/CategoryInput.tsx
  frontend/src/components/trip/TripItemAddModal/DateInput/DateInput.tsx
  frontend/src/components/trip/TripItemAddModal/ExpenseInput/ExpenseInput.style.ts
  frontend/src/components/trip/TripItemAddModal/ExpenseInput/ExpenseInput.tsx
  frontend/src/components/trip/TripItemAddModal/MemoInput/MemoInput.style.ts
  frontend/src/components/trip/TripItemAddModal/MemoInput/MemoInput.tsx
  frontend/src/components/trip/TripItemAddModal/PlaceInput/PlaceInput.style.ts
  frontend/src/components/trip/TripItemAddModal/PlaceInput/PlaceInput.tsx
  frontend/src/components/trip/TripItemAddModal/StarRatingInput/StarRatingInput.tsx
  frontend/src/components/trip/TripItemAddModal/TitleInput/TitleInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.style.ts
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemCategoryInput/TripItemCategoryInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemExpenseInput/TripItemExpenseInput.tsx
  frontend/src/constants/trip.ts
  frontend/src/constants/ui.ts
  frontend/src/hooks/trip/useAddTripItemForm.ts
  frontend/src/hooks/trip/useTripDates.ts
  frontend/src/hooks/trip/useTripItemExpenseInput.ts
  frontend/src/hooks/trip/useTripItemPlaceInput.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/tripItem.ts
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/styles/index.ts
  frontend/src/types/tripItem.ts
Labels: ✨ Feature, FE

#129 DayLog의 Item들 순서 변경 기능 구현
  backend/src/docs/asciidoc/docs.adoc
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/dto/request/ItemsOrdinalUpdateRequest.java
  backend/src/main/java/hanglog/trip/presentation/DayLogController.java
  backend/src/main/java/hanglog/trip/service/DayLogService.java
  backend/src/test/java/hanglog/trip/fixture/ItemFixture.java
  backend/src/test/java/hanglog/trip/presentation/DayLogControllerTest.java
  backend/src/test/java/hanglog/trip/service/DayLogServiceTest.java
Labels: ✨ Feature, BE

#140 refactor: API명세 수정에 따른 trips fetch 로직 리팩토링
  frontend/src/api/trips/trips.ts
  frontend/src/mocks/handlers/trips.ts
Labels: 🔨 Refactor

#134 검색어 관련 제안 목록 보여주는 기능 debounce 적용
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/components/common/CitySuggestion/CitySuggestion.style.ts
  frontend/src/hooks/common/useDebounce.ts
  frontend/src/mocks/data/city.ts
Labels: ✨ Feature, FE

#141 Docker + Nginx 배포환경 구축
  frontend/docker-compose.yml
  frontend/nginx.conf
Labels: 🌏 Environment

#39 소셜 로그인 구현
  backend/src/main/java/hanglog/member/Member.java
  backend/src/main/java/hanglog/member/MemberState.java
  backend/src/main/java/hanglog/member/controller/OAuthLoginController.java
  backend/src/main/java/hanglog/member/provider/GoogleProperties.java
  backend/src/main/java/hanglog/member/provider/KakaoProperties.java
  backend/src/main/java/hanglog/member/provider/Provider.java
  backend/src/main/java/hanglog/member/provider/ProviderProperties.java
  backend/src/main/java/hanglog/member/repository/MemberRepository.java
  backend/src/main/java/hanglog/member/service/OAuthLoginService.java
  backend/src/main/java/hanglog/member/service/dto/AccessTokenRequestDto.java
  backend/src/main/java/hanglog/member/service/dto/AccessTokenResponseDto.java
  backend/src/main/java/hanglog/member/service/dto/GoogleUserInfoResponseDto.java
  backend/src/main/java/hanglog/member/service/dto/KakaoUserInfoResponseDto.java
  backend/src/main/java/hanglog/member/service/dto/UserInfoDto.java
  backend/src/main/resources/application.yml
  backend/src/test/java/hanglog/member/provider/fixture/MemberFixture.java
Labels: ✨ Feature, BE

#138 Environment/#130 Jacoco통한 테스트 커버리지 측정 및 자동화 설정
  .github/workflows/gradle.yml
  backend/build.gradle
Labels: 🌏 Environment, BE

#151 Trips 폴더를 trips로 네이밍 변경
  frontend/src/components/trips/TripsHeader/TripsHeader.tsx
  frontend/src/components/trips/TripsItem/TripsItem.style.ts
  frontend/src/components/trips/TripsItem/TripsItem.tsx
  frontend/src/components/trips/TripsItem/TripsItemSkeleton.tsx
  frontend/src/components/trips/TripsItemList/TripsItemList.style.ts
  frontend/src/components/trips/TripsItemList/TripsItemList.tsx
  frontend/src/components/trips/TripsItemList/TripsItemListSkeleton.tsx
  frontend/src/components/trips/TutorialModal/TutorialModal.style.ts
  frontend/src/components/trips/TutorialModal/TutorialModal.tsx
Labels: 🔨 Refactor, FE

#144 BaseUrl 프로토콜 지정
  frontend/src/constants/api.ts
Labels: 🌏 Environment, FE

#149 TripsPage 리팩토링
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/trips/getTrips.ts
  frontend/src/assets/png/trip_default-thumbnail.png
  frontend/src/assets/svg/TripsHeader.svg
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/components/layout/Header/Header.style.ts
  frontend/src/components/trips/TripsHeader/TripsHeader.style.ts
  frontend/src/components/trips/TripsHeader/TripsHeader.tsx
  frontend/src/components/trips/TripsItem/TripsItem.style.ts
  frontend/src/components/trips/TripsItem/TripsItem.tsx
  frontend/src/components/trips/TripsItem/TripsItemSkeleton.tsx
  frontend/src/components/trips/TripsItemList/TripsItemList.tsx
  frontend/src/components/trips/TripsItemList/TripsItemListSkeleton.tsx
  frontend/src/constants/path.ts
  frontend/src/hooks/api/useTripsQuery.ts
  frontend/src/mocks/data/trips.ts
  frontend/src/pages/TripsPage/TripsPage.tsx
  frontend/src/router/AppRouter.tsx
Labels: 🔨 Refactor, FE

#154 feat: SSL/TLS 인증서 적용을 위한 Docker certbot 볼륨 마운트
  frontend/docker-compose.yml
  frontend/nginx.conf
Labels: 🌏 Environment

#137 Trip과 DayLog 영속 관계 수정
  backend/src/main/java/hanglog/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/hanglog/trip/domain/DayLog.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/service/TripService.java
Labels: 🐞 Bug, BE

#132 여행 정보(이름, 날짜, 도시, 설명, 대표사진) 수정 모달 구현
  frontend/src/App.tsx
  frontend/src/api/trip/putTrip.ts
  frontend/src/api/trips/postNewTrip.ts
  frontend/src/assets/svg/warning-icon.svg
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/components/common/CitySuggestion/CitySuggestion.style.ts
  frontend/src/components/common/DateInput/DateInput.tsx
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/newTrip/NewTripForm/TripCreateForm.style.ts
  frontend/src/components/newTrip/NewTripForm/TripCreateForm.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.style.ts
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/hooks/api/useCreateTripMutation.ts
  frontend/src/hooks/api/useTripEditMutation.ts
  frontend/src/hooks/common/useCityDateForm.ts
  frontend/src/hooks/newTrip/useNewTripForm.ts
  frontend/src/hooks/trip/useTripEditForm.ts
  frontend/src/mocks/handlers/trips.ts
  frontend/src/pages/TripCreatePage/TripCreatePage.tsx
  frontend/src/stories/common/CitySearchBar.stories.tsx
  frontend/src/types/trip.ts
Labels: ✨ Feature, FE

#158 카테고리 목록 조회 API 구현
  backend/src/docs/asciidoc/docs.adoc
  backend/src/main/java/hanglog/category/domain/Category.java
  backend/src/main/java/hanglog/category/domain/repository/CategoryRepository.java
  backend/src/main/java/hanglog/category/dto/CategoryResponse.java
  backend/src/main/java/hanglog/category/presentation/CategoryController.java
  backend/src/main/java/hanglog/category/repository/CategoryRepository.java
  backend/src/main/java/hanglog/category/service/CategoryService.java
  backend/src/main/java/hanglog/expense/Expense.java
  backend/src/main/java/hanglog/trip/domain/Place.java
  backend/src/main/java/hanglog/trip/dto/response/ExpenseResponse.java
  backend/src/main/java/hanglog/trip/dto/response/PlaceResponse.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/category/fixture/CategoryFixture.java
  backend/src/test/java/hanglog/category/presentation/CategoryControllerTest.java
  backend/src/test/java/hanglog/category/service/CategoryServiceTest.java
  backend/src/test/java/hanglog/trip/fixture/ExpenseFixture.java
  backend/src/test/java/hanglog/trip/fixture/PlaceFixture.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: ✨ Feature, BE

#156 Storybook 배포
  frontend/nginx.conf
Labels: 🌏 Environment, FE

#157 TripEditPage 리팩토링
  frontend/src/components/common/DayLogItem/DayLogItem.tsx
  frontend/src/components/common/DayLogItem/TitleInput/TitleInput.tsx
  frontend/src/components/common/DayLogList/DayLogList.tsx
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/common/TripItem/EditMenu/EditMenu.style.ts
  frontend/src/components/common/TripItem/EditMenu/EditMenu.tsx
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/hooks/api/useAddTripItemMutation.ts
  frontend/src/hooks/api/useDayLogOrderMutation.ts
  frontend/src/hooks/api/useDayLogTitleMutation.ts
  frontend/src/hooks/api/useDeleteTripItemMutation.ts
  frontend/src/hooks/api/useExpenseCategoryQuery.ts
  frontend/src/hooks/api/useUpdateTripItemMutation.ts
  frontend/src/hooks/common/useDraggedItem.ts
  frontend/src/hooks/trip/useAddTripItemForm.ts
  frontend/src/hooks/trip/useTripDates.ts
  frontend/src/mocks/handlers/tripItem.ts
  frontend/src/pages/TripEditPage/TripEditPage.style.ts
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/stories/common/DayLogList.stories.tsx
Labels: 🔨 Refactor, FE

#162 Item 수정 요청시 isPlaceUpdated로 판단 로직 추가
  backend/src/main/java/hanglog/trip/dto/request/ItemUpdateRequest.java
  backend/src/main/java/hanglog/trip/presentation/ItemController.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/trip/presentation/ItemControllerTest.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: 🔨 Refactor, BE

#170 Location 헤더 설정 추가
  backend/src/main/java/hanglog/config/CorsConfig.java
Labels: 🌏 Environment, BE

#159 도시 검색 기능 특수문자 작성시 버그 수정 + 검색어와 매칭되는 제안도시가 하나일 시 엔터로 적용가능
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/components/common/CitySuggestion/CitySuggestion.tsx
  frontend/src/components/common/DateInput/DateInput.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.style.ts
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/constants/regex.ts
  frontend/src/hooks/common/useCitySuggestion.ts
  frontend/src/utils/formatter.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#173 트립 생성 시 Location 헤더 값 처리 버그 수정
  frontend/src/api/trip/postTrip.ts
  frontend/src/components/trip/TripCreateForm/TripCreateForm.style.ts
  frontend/src/components/trip/TripCreateForm/TripCreateForm.tsx
  frontend/src/hooks/api/useCreateTripMutation.ts
  frontend/src/mocks/handlers/trips.ts
  frontend/src/pages/TripCreatePage/TripCreatePage.tsx
Labels: 🐞 Bug, 🔨 Refactor, FE

#176 초 기본적인 로깅 구현
  backend/.gitignore
  backend/src/main/java/hanglog/global/exception/GlobalExceptionHandler.java
  backend/src/main/resources/logback-spring.xml
Labels: ✨ Feature, BE

#180 eslint 설정 수정
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/trip/postTrip.ts
  frontend/src/assets/index.d.ts
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/components/common/DateInput/DateInput.tsx
  frontend/src/components/common/DayLogItem/DayLogItem.tsx
  frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
  frontend/src/components/common/StarRating/Star/Star.tsx
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/components/layout/Header/Header.style.ts
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/trip/TripItemAddModal/DateInput/DateInput.tsx
  frontend/src/components/trips/TripsItem/TripsItem.tsx
  frontend/src/components/trips/TutorialModal/TutorialModal.tsx
  frontend/src/hooks/api/useCityQuery.ts
  frontend/src/hooks/api/useCreateTripMutation.ts
  frontend/src/hooks/api/useDeleteTripItemMutation.ts
  frontend/src/hooks/api/useTripEditMutation.ts
  frontend/src/hooks/api/useTripQuery.ts
  frontend/src/hooks/api/useUpdateTripItemMutation.ts
  frontend/src/hooks/common/useCitySuggestion.ts
  frontend/src/hooks/common/useDragAndDrop.ts
  frontend/src/hooks/trip/useTripDates.ts
  frontend/src/hooks/trip/useTripEditForm.ts
  frontend/src/hooks/trip/useTripItemExpenseInput.ts
  frontend/src/hooks/trip/useTripItemPlaceInput.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/dayLog.ts
  frontend/src/mocks/handlers/tripItem.ts
  frontend/src/stories/common/DayLogList.stories.tsx
  frontend/src/stories/common/TripsItemList.stories.tsx
  frontend/src/stories/common/TripsItemListEmpty.stories.tsx
  frontend/src/types/dayLog.ts
  frontend/src/types/tripItem.ts
  frontend/src/utils/formatter.ts
  frontend/src/utils/typeGuard.ts
Labels: 🐞 Bug, 🌏 Environment, FE

#178 TripEditPage 웹 접근성 개선
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/components/common/CitySuggestion/CitySuggestion.tsx
  frontend/src/components/common/DateInput/DateInput.tsx
  frontend/src/components/common/DayLogItem/DayLogItem.tsx
  frontend/src/components/common/TripItem/EditMenu/EditMenu.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/components/trip/TripItemAddModal/DateInput/DateInput.tsx
  frontend/src/components/trip/TripItemAddModal/ExpenseInput/ExpenseInput.tsx
  frontend/src/components/trip/TripItemAddModal/MemoInput/MemoInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.style.ts
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/hooks/common/useAutoScroll.ts
  frontend/src/hooks/common/useCityDateForm.ts
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/stories/common/DateInput.stories.tsx
  frontend/src/types/trips.ts
  frontend/src/utils/formatter.ts
Labels: 🔨 Refactor, FE

#184 TripsPage 웹 접근성 개선
  frontend/src/components/trips/TripsItem/TripsItem.tsx
  frontend/src/components/trips/TripsItemList/TripsItemList.tsx
Labels: 🔨 Refactor, FE

#188 지도 기능 구현
  frontend/src/App.tsx
  frontend/src/assets/svg/pin-icon.svg
  frontend/src/assets/svg/selected-pin-icon.svg
  frontend/src/components/common/GoogleMapWrapper/GoogleMapWrapper.tsx
  frontend/src/components/common/MapDashedLine/MapDashedLine.tsx
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/components/common/TripItemMarker/TripItemMarker.tsx
  frontend/src/components/common/TripItemMarkerContainer/TripItemMarkerContainer.tsx
  frontend/src/components/common/TripMap/TripMap.tsx
  frontend/src/components/layout/Footer/Footer.style.ts
  frontend/src/components/layout/Footer/Footer.tsx
  frontend/src/constants/map.ts
  frontend/src/hooks/common/useScrollFocus.ts
  frontend/src/mocks/data/city.ts
  frontend/src/mocks/data/trip.ts
  frontend/src/mocks/data/trips.ts
  frontend/src/mocks/handlers/tripItem.ts
  frontend/src/pages/TripEditPage/TripEditPage.style.ts
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/store/scrollFocus.ts
  frontend/src/stories/common/CitySearchBar.stories.tsx
  frontend/src/types/city.ts
  frontend/src/types/trip.ts
Labels: ✨ Feature, FE

#197 package.json dependencies 수정
  frontend/package.json
Labels: 🌏 Environment, FE

#199 package.json dependencies 수정
  frontend/package-lock.json
Labels: 🌏 Environment, 🔨 Refactor, FE

#190 로그 디렉터리 찾지 못하는 문제 해결
  backend/src/main/resources/logback-spring.xml
Labels: 🐞 Bug, BE
