Repository woowacourse-teams/2023-hang-log, pull requests merged in 2023-12, with the labels that each got.

#760 리액트 쿼리 버전 업
  frontend/package-lock.json
  frontend/package.json
Labels: ✨ Feature, FE

#762 refactor/#761: suspense 사용하는 useQuery를 useSuspenseQuery로 교체
  frontend/package-lock.json
  frontend/package.json
  frontend/src/constants/trip.ts
  frontend/src/hooks/api/queryClient.ts
  frontend/src/hooks/api/useCityQuery.ts
  frontend/src/hooks/api/useCommunityTripQuery.ts
  frontend/src/hooks/api/useCommunityTripsQuery.ts
  frontend/src/hooks/api/useDayLogTitleMutation.ts
  frontend/src/hooks/api/useExpenseCategoryQuery.ts
  frontend/src/hooks/api/useExpenseQuery.ts
  frontend/src/hooks/api/useRecommendedTripsQuery.ts
  frontend/src/hooks/api/useSharedTripQuery.ts
  frontend/src/hooks/api/useTripEditPageQueries.ts
  frontend/src/hooks/api/useTripQuery.ts
  frontend/src/hooks/api/useTripsQuery.ts
  frontend/src/hooks/api/useUserInfoMutation.ts
  frontend/src/hooks/api/useUserInfoQuery.ts
  frontend/src/hooks/common/useMultipleImageUpload.ts
  frontend/src/hooks/common/useSingleImageUpload.ts
  frontend/src/pages/CommunityPage/CommunityPage.tsx
  frontend/src/pages/CommunityTripPage/CommunityTripPage.tsx
  frontend/src/pages/SharedPage/SharedTripPage.tsx
Labels: ✨ Feature, FE

#765 도시 중복 조회 오류 수정
  backend/src/main/java/hanglog/trip/domain/TripCity.java
  backend/src/test/java/hanglog/integration/controller/TripIntegrationTest.java
Labels: 🐞 Bug, BE

#767 QueryKey 불일치로 인해 발생하는 문제 해결
  frontend/src/hooks/api/useCommunityTripQuery.ts
  frontend/src/hooks/api/useExpenseQuery.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#769 queryKey불일치로 인한 myTrip 상세정보 페이지 오류 수정
  frontend/cypress/e2e/createTrip.cy.ts
  frontend/src/hooks/api/useAddTripItemMutation.ts
  frontend/src/hooks/api/useCommunityTripQuery.ts
  frontend/src/hooks/api/useDayLogOrderMutation.ts
  frontend/src/hooks/api/useDeleteTripItemMutation.ts
  frontend/src/hooks/api/useExpenseQuery.ts
  frontend/src/hooks/api/useTripEditMutation.ts
  frontend/src/hooks/api/useTripEditPageQueries.ts
  frontend/src/hooks/api/useTripPublishMutation.ts
  frontend/src/hooks/api/useTripQuery.ts
  frontend/src/hooks/api/useTripShareStatusMutation.ts
  frontend/src/hooks/api/useUpdateTripItemMutation.ts
  frontend/src/hooks/expense/useExpense.ts
  frontend/src/hooks/trip/useTrip.ts
  frontend/src/pages/TripPage/TripMobilePage.tsx
Labels: 🐞 Bug, 🔨 Refactor, FE

#770 에러 추적 개선을 위한 Sentry 환경 구축
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/interceptors.ts
  frontend/src/components/common/Error/Error.tsx
  frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
  frontend/src/index.tsx
Labels: 🌏 Environment, ✨ Feature, FE
