Repository woowacourse-teams/2023-hang-log, pull requests merged in 2023-08, with the labels that each got.

#202 CI/CD 실패로 인한 의존성 수정
  frontend/package-lock.json
  frontend/package.json
Labels: 🌏 Environment, 🔨 Refactor, FE

#201 각 로깅 레벨 별 설정 파일 분리
  backend/src/main/resources/console-appender.xml
  backend/src/main/resources/error-appender.xml
  backend/src/main/resources/info-appender.xml
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logback.xml
  backend/src/main/resources/warn-appender.xml
Labels: 🔨 Refactor, BE

#161 경비 조회 기능 구현
  backend/src/docs/asciidoc/docs.adoc
  backend/src/main/java/hanglog/city/dto/response/CityResponse.java
  backend/src/main/java/hanglog/expense/domain/CategoryExpense.java
  backend/src/main/java/hanglog/expense/domain/Currency.java
  backend/src/main/java/hanglog/expense/domain/DayLogExpense.java
  backend/src/main/java/hanglog/expense/domain/Expense.java
  backend/src/main/java/hanglog/expense/domain/repository/CurrencyRepository.java
  backend/src/main/java/hanglog/expense/domain/repository/ExpenseRepository.java
  backend/src/main/java/hanglog/expense/domain/type/CurrencyType.java
  backend/src/main/java/hanglog/expense/dto/response/CategoryExpenseResponse.java
  backend/src/main/java/hanglog/expense/dto/response/CurrencyRateResponse.java
  backend/src/main/java/hanglog/expense/dto/response/DayLogExpenseResponse.java
  backend/src/main/java/hanglog/expense/dto/response/ExchangeRateResponse.java
  backend/src/main/java/hanglog/expense/dto/response/ItemDetailResponse.java
  backend/src/main/java/hanglog/expense/dto/response/ItemExpenseResponse.java
  backend/src/main/java/hanglog/expense/dto/response/TripExpenseResponse.java
  backend/src/main/java/hanglog/expense/presentation/ExpenseController.java
  backend/src/main/java/hanglog/expense/service/ExpenseService.java
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/main/java/hanglog/trip/domain/DayLog.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/dto/response/CityWithPositionResponse.java
  backend/src/main/java/hanglog/trip/dto/response/DayLogGetResponse.java
  backend/src/main/java/hanglog/trip/dto/response/ItemResponse.java
  backend/src/main/java/hanglog/trip/presentation/CityController.java
  backend/src/main/java/hanglog/trip/service/CityService.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/expense/fixture/CurrencyFixture.java
  backend/src/test/java/hanglog/expense/presentation/ExpenseControllerTest.java
  backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
  backend/src/test/java/hanglog/trip/fixture/CityFixture.java
  backend/src/test/java/hanglog/trip/fixture/DayLogFixture.java
  backend/src/test/java/hanglog/trip/fixture/ExpenseFixture.java
  backend/src/test/java/hanglog/trip/fixture/ItemFixture.java
  backend/src/test/java/hanglog/trip/fixture/TripFixture.java
  backend/src/test/java/hanglog/trip/presentation/CityControllerTest.java
  backend/src/test/java/hanglog/trip/service/CityServiceTest.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: ✨ Feature, BE

#185 TripEditPage에서 뜨는 msw버그 수정
  frontend/src/App.tsx
  frontend/src/api/city/getCity.ts
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/constants/api.ts
  frontend/src/hooks/api/useCityQuery.ts
  frontend/src/mocks/handlers/city.ts
Labels: 🐞 Bug, FE

#206 경비 api 리펙터링
  backend/src/main/java/hanglog/expense/domain/type/CurrencyType.java
  backend/src/main/java/hanglog/expense/dto/response/CurrencyRateResponse.java
  backend/src/main/java/hanglog/expense/dto/response/ExchangeRateResponse.java
  backend/src/main/java/hanglog/expense/dto/response/TripExpenseResponse.java
Labels: 🔨 Refactor, BE

#212 Dotenv, CopyWebpackPlugin development 환경에서만 돌도록 수정
  frontend/webpack.config.js
Labels: 🌏 Environment, 🔨 Refactor, FE

#208 Footer 제대로 안 위치하는 문제 해결
  frontend/src/mocks/handlers/city.ts
  frontend/src/pages/TripCreatePage/TripCreatePage.style.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#217 스토리북에서 msw 안 작동하는 문제 해결
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/src/stories/common/DayLogList.stories.tsx
Labels: 🐞 Bug, 🔨 Refactor, FE

#214 TripEditPage path 수정
  frontend/src/components/trip/TripCreateForm/TripCreateForm.tsx
  frontend/src/constants/path.ts
  frontend/src/router/AppRouter.tsx
Labels: 🔨 Refactor, FE

#222 webpack config에서 process.env.NODE_ENV를 읽어오지 못하는 문제 해결
  frontend/package.json
Labels: 🐞 Bug, 🌏 Environment, FE

#223 fix: webpack config에서 process.env.NODE_ENV를 읽어오지 못하는 문제 해결 시도
  frontend/package.json
Labels: 🐞 Bug, 🌏 Environment, FE

#224 process.env문제 해결을 위한 webpack dotenv설정 복구
  frontend/webpack.config.js
Labels: 🐞 Bug, 🌏 Environment, FE

#192 TripItemAddModal 이미지 업로드 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/image/postImage.ts
  frontend/src/components/trip/TripItemAddModal/ImageInput/ImageInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/constants/api.ts
  frontend/src/hooks/api/useImageMutation.ts
  frontend/src/hooks/common/useImageUpload.ts
  frontend/src/mocks/data/image.ts
  frontend/src/mocks/handlers/image.ts
  frontend/src/mocks/handlers/index.ts
Labels: ✨ Feature, FE

#230 RestDocs constraint 추가
  backend/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: 🌏 Environment, BE

#219 실패토스트 & storybook 오류
  frontend/src/assets/svg/warning-icon.svg
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/components/common/CitySuggestion/CitySuggestion.tsx
  frontend/src/components/trip/TripCreateForm/TripCreateForm.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/hooks/api/useCreateTripMutation.ts
  frontend/src/hooks/api/useTripEditMutation.ts
  frontend/src/hooks/common/useCitySuggestion.ts
  frontend/src/hooks/trip/useTripEditForm.ts
  frontend/src/stories/common/CitySearchBar.stories.tsx
  frontend/src/stories/common/DateInput.stories.tsx
Labels: 🐞 Bug, 🔨 Refactor, ✨ Feature, FE

#234 image post 요청 response body 타입 수정
  frontend/src/api/image/postImage.ts
  frontend/src/hooks/common/useImageUpload.ts
  frontend/src/types/image.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#203 ExpensePage 구현
  frontend/src/api/expense/getExpense.ts
  frontend/src/components/common/DonutChart/DonutChart.tsx
  frontend/src/components/expense/ExpenseCategories/ExpenseCategories.style.ts
  frontend/src/components/expense/ExpenseCategories/ExpenseCategories.tsx
  frontend/src/components/expense/ExpenseCategoryInformation/ExpenseCategoryInformation.style.ts
  frontend/src/components/expense/ExpenseCategoryInformation/ExpenseCategoryInformation.tsx
  frontend/src/components/expense/ExpenseCategoryInformation/ExpenseCategoryInformationSkeleton.tsx
  frontend/src/components/expense/ExpenseDates/ExpenseDates.style.ts
  frontend/src/components/expense/ExpenseDates/ExpenseDates.tsx
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.style.ts
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.tsx
  frontend/src/components/expense/ExpenseInformation/ExpenseInformationSkeleton.tsx
  frontend/src/components/expense/ExpenseItem/ExpenseItem.style.ts
  frontend/src/components/expense/ExpenseItem/ExpenseItem.tsx
  frontend/src/components/expense/ExpenseItem/ExpenseItemSkeleton.tsx
  frontend/src/components/expense/ExpenseList/ExpenseList.style.ts
  frontend/src/components/expense/ExpenseList/ExpenseList.tsx
  frontend/src/components/expense/ExpenseList/ExpenseListSkeleton.tsx
  frontend/src/components/expense/ExpenseListSection/ExpenseListSection.style.ts
  frontend/src/components/expense/ExpenseListSection/ExpenseListSection.tsx
  frontend/src/components/expense/ExpenseListSection/ExpenseListSectionSkeleton.tsx
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSection.style.ts
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSection.tsx
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSectionSkeleton.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/expense.ts
  frontend/src/constants/path.ts
  frontend/src/constants/ui.ts
  frontend/src/hooks/api/useExpenseQuery.ts
  frontend/src/hooks/expense/useExpense.ts
  frontend/src/mocks/data/expense.ts
  frontend/src/mocks/handlers/expense.ts
  frontend/src/pages/ExpensePage/ExpensePage.style.ts
  frontend/src/pages/ExpensePage/ExpensePage.tsx
  frontend/src/pages/ExpensePage/ExpensePageSkeleton.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/types/expense.ts
  frontend/src/utils/chart.ts
Labels: ✨ Feature, FE

#238 행록 디자인 시스템 버전 업데이트
  frontend/package-lock.json
  frontend/package.json
Labels: 🌏 Environment, FE

#189 TripPage 구현
  frontend/src/api/trip/deleteTrip.ts
  frontend/src/assets/svg/share-icon.svg
  frontend/src/components/common/DayLogItem/DayLogItem.tsx
  frontend/src/components/common/DayLogItem/TitleInput/TitleInput.tsx
  frontend/src/components/common/DayLogList/DayLogList.tsx
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.style.ts
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
  frontend/src/components/common/TripInformation/TripEditButtons/TripEditButtons.style.ts
  frontend/src/components/common/TripInformation/TripEditButtons/TripEditButtons.tsx
  frontend/src/components/common/TripInformation/TripInformation.style.ts
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/common/TripItem/TripItem.style.ts
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/components/common/TripItem/TripItemSkeleton.tsx
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/components/trips/TripsItem/TripsItem.tsx
  frontend/src/components/trips/TripsItemList/TripsItemList.tsx
  frontend/src/constants/path.ts
  frontend/src/hooks/api/useDeleteTripMutation.ts
  frontend/src/mocks/handlers/trips.ts
  frontend/src/pages/TripPage/TripPage.style.ts
  frontend/src/pages/TripPage/TripPage.tsx
  frontend/src/pages/TripPage/TripPageSkeleton.tsx
  frontend/src/router/AppRouter.tsx
Labels: ✨ Feature, FE

#231 Item생성시 Place Category를 가져오는 기능구현
  backend/src/main/java/hanglog/category/domain/repository/CategoryRepository.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/trip/fixture/PlaceFixture.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: ✨ Feature, BE

#244 반환하는 에러 로그 메시지 변경
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/main/java/hanglog/global/exception/GlobalExceptionHandler.java
Labels: 🔨 Refactor, BE

#239 Trip 전체 및 단일 조회 CityResponse로 수정
  backend/src/main/java/hanglog/trip/dto/response/CityWithPositionResponse.java
  backend/src/main/java/hanglog/trip/dto/response/TripResponse.java
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
Labels: 🔨 Refactor, BE

#247 아이템 조회시 이미지 url 타입 변경
  backend/src/main/java/hanglog/trip/dto/response/ItemResponse.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
Labels: 🔨 Refactor, BE

#243 가계부 클릭 PATH 수정
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
  frontend/src/constants/path.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#225 스토리북 스토리 & 설정 추가
  frontend/.storybook/main.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/stories/common/Error.stories.tsx
  frontend/src/stories/common/TripMap.stories.tsx
  frontend/src/stories/layout/Footer.stories.tsx
  frontend/src/stories/layout/Header.stories.tsx
  frontend/src/stories/trip/CategoryInput.stories.tsx
  frontend/src/stories/trip/DateInput.stories.tsx
  frontend/src/stories/trip/ExpenseInput.stories.tsx
  frontend/src/stories/trip/MemoInput.stories.tsx
  frontend/src/stories/trip/PlaceInput.stories.tsx
  frontend/src/stories/trip/StarRatingInput.stories.tsx
  frontend/src/stories/trip/TitleInput.stories.tsx
  frontend/src/stories/trip/TripCreateForm.stories.tsx
  frontend/src/stories/trip/TripInfoEditModal.stories.tsx
  frontend/src/stories/trip/TripItemAddModal.stories.tsx
  frontend/src/stories/trips/TripsHeader.stories.tsx
  frontend/src/stories/trips/TripsItem.stories.tsx
  frontend/src/stories/trips/TripsItemList.stories.tsx
  frontend/src/stories/trips/TripsItemListEmpty.stories.tsx
  frontend/src/stories/trips/TutorialModal.stories.tsx
Labels: ✨ Feature, FE

#260 TripPage에서 더보기 버튼 2개로 보이는 문제 해결
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.style.ts
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
Labels: 🐞 Bug, 🔨 Refactor, FE

#259 여행 처음 생성 후 소제목 입력시 모든 day log 탭에서 같은 소제목 보이는 문제 해결
  frontend/src/components/common/DayLogItem/TitleInput/TitleInput.tsx
  frontend/src/hooks/api/useDayLogTitleMutation.ts
  frontend/src/stories/trips/TripsItem.stories.tsx
Labels: 🐞 Bug, 🔨 Refactor, FE

#254 TripItem 목록 정렬 후 보여주기
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/utils/sortByStartDate.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#227 지도 마커 라벨 추가
  frontend/src/assets/svg/pin-icon.svg
  frontend/src/assets/svg/selected-pin-icon.svg
  frontend/src/components/common/TripItemMarker/TripItemMarker.style.ts
  frontend/src/components/common/TripItemMarker/TripItemMarker.tsx
  frontend/src/components/common/TripItemMarkerContainer/TripItemMarkerContainer.tsx
  frontend/src/constants/map.ts
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/types/trip.ts
Labels: ✨ Feature, FE

#264 Rating nullable로 변경 및 최소제한해제
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/dto/request/ItemRequest.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
Labels: 🔨 Refactor, BE

#269 타입 에러 버그 해결
  frontend/src/pages/TripPage/TripPage.tsx
  frontend/src/stories/common/TripMap.stories.tsx
Labels: 🐞 Bug, 🔨 Refactor, FE

#267 Toast 목록 전역 상태로 관리
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/dayLog/patchDayLogItemOrder.ts
  frontend/src/api/dayLog/patchDayLogTitle.ts
  frontend/src/api/image/postImage.ts
  frontend/src/api/trip/deleteTrip.ts
  frontend/src/api/trip/postTrip.ts
  frontend/src/api/trip/putTrip.ts
  frontend/src/api/tripItem/deleteTripItem.ts
  frontend/src/api/tripItem/postTripItem.ts
  frontend/src/api/tripItem/putTripItem.ts
  frontend/src/components/common/DayLogItem/TitleInput/TitleInput.tsx
  frontend/src/components/common/ToastContainer/ToastContainer.tsx
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
  frontend/src/components/common/TripItem/EditMenu/EditMenu.tsx
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/components/trip/TripCreateForm/TripCreateForm.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/components/trip/TripItemAddModal/ImageInput/ImageInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/hooks/api/useAddTripItemMutation.ts
  frontend/src/hooks/api/useCreateTripMutation.ts
  frontend/src/hooks/api/useDayLogOrderMutation.ts
  frontend/src/hooks/api/useDayLogTitleMutation.ts
  frontend/src/hooks/api/useDeleteTripItemMutation.ts
  frontend/src/hooks/api/useDeleteTripMutation.ts
  frontend/src/hooks/api/useImageMutation.ts
  frontend/src/hooks/api/useTripEditMutation.ts
  frontend/src/hooks/api/useUpdateTripItemMutation.ts
  frontend/src/hooks/common/useImageUpload.ts
  frontend/src/hooks/trip/useTripEditForm.ts
  frontend/src/store/toast.ts
  frontend/src/types/toast.ts
  frontend/src/utils/uniqueId.ts
Labels: 🔨 Refactor, FE

#273 trips페이지에서 튜토리얼 창이 닫히지 않는 문제 해결
  frontend/package-lock.json
  frontend/package.json
Labels: FE

#272 expense NPE 수정
  backend/src/main/java/hanglog/expense/dto/response/DayLogExpenseResponse.java
Labels: 🐞 Bug, BE

#275 운영체제간 환경변수 호환을 위한 cross-env 반영
  frontend/package-lock.json
  frontend/package.json
Labels: 🌏 Environment, FE

#278 버튼 2개 문제 해결
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
  frontend/src/components/common/TripItemList/TripItemList.tsx
Labels: 🐞 Bug, 🔨 Refactor, FE

#279 Trip 생성 시 날짜 계산 방식 변경
  backend/src/main/java/hanglog/trip/service/TripService.java
Labels: 🐞 Bug, BE

#262 환율 데이터가 없을시 가장 최근 환율 반영
  backend/src/main/java/hanglog/expense/domain/Currency.java
  backend/src/main/java/hanglog/expense/domain/repository/CurrencyRepository.java
  backend/src/main/java/hanglog/expense/service/ExpenseService.java
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/test/java/hanglog/expense/domain/repository/CurrencyRepositoryTest.java
  backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
Labels: ✨ Feature, BE

#282 hotfix repositoryTest 제거
  backend/src/test/java/hanglog/expense/domain/repository/CurrencyRepositoryTest.java
Labels: 🐞 Bug, BE

#285 ItemUpdate시 별점 nullable 허용 로직 추가
  backend/src/main/java/hanglog/trip/dto/request/ItemUpdateRequest.java
Labels: 🐞 Bug, BE

#287 Flex때문에 badge 찌부되는 문제 해결
  frontend/src/components/common/TripInformation/TripInformation.style.ts
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.style.ts
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.tsx
Labels: 🐞 Bug, 🔨 Refactor, FE

#288 category 및 daylog 항상 포함
  backend/src/main/java/hanglog/expense/service/ExpenseService.java
  backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
Labels: ✨ Feature, BE

#283 TripItemAddModal, DateInput에서 dates 불러서 사용하도록 수정
  frontend/src/components/trip/TripItemAddModal/DateInput/DateInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/stories/trip/DateInput.stories.tsx
Labels: 🔨 Refactor, FE

#291 아이템 수정할 때 기타에서 장소로 변경할 때 에러 보여주기
  frontend/src/hooks/trip/useAddTripItemForm.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#266 여행정보 수정 모달, 대표이미지 삭제, 추가 가능
  frontend/src/components/trip/TripInfoEditModal/ImageInput/ImageInput.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/components/trip/TripItemAddModal/ImageInput/ImageInput.tsx
  frontend/src/hooks/trip/useTripEditForm.ts
Labels: ✨ Feature, FE

#293 Item Spot과 Nonspot간 변환시 Place 설정 추가
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/main/java/hanglog/trip/dto/request/ItemRequest.java
  backend/src/main/java/hanglog/trip/dto/request/ItemUpdateRequest.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
Labels: 🐞 Bug, BE

#295 홈으로 가기 클릭했을 때 홈으로 안 가고 새로고침되는 문제 해결
  frontend/package.json
  frontend/src/hooks/common/useResetError.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#301 통화 기호랑 금액 사이 공백 제거
  frontend/src/components/expense/ExpenseCategoryInformation/ExpenseCategoryInformation.tsx
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSection.tsx
Labels: 🔨 Refactor, FE

#303 TripEditPage에서 아이템 추가 버튼 클릭하면 지도 줌 인/아웃 되는 문제 해결
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/pages/TripPage/TripPage.tsx
Labels: 🐞 Bug, FE

#307 가계부 페이지 경비 없을 때 파이 차트에 100% 보이는 버그 수정
  frontend/src/components/common/DonutChart/DonutChart.tsx
Labels: 🐞 Bug, 🔨 Refactor, FE

#310 Trip 업데이트 시 요청받은 제목으로 수정
  backend/src/main/java/hanglog/trip/service/TripService.java
Labels: 🐞 Bug, BE

#306 Trip 업데이트 시 날짜 계산 방식 변경
  backend/src/main/java/hanglog/trip/service/TripService.java
Labels: 🐞 Bug, BE

#318 npm run build 스크립트 추가
  frontend/package.json
Labels: 🐞 Bug, FE

#304 TripCreatePage 웹접근성 & 모달 웹접근성 향상
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/DateInput/DateInput.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.style.ts
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
Labels: 🔨 Refactor, ✨ Feature, FE

#313 items 오름차순으로 정렬
  backend/src/main/java/hanglog/trip/domain/DayLog.java
Labels: 🔨 Refactor, BE

#312 ExpensePage DayLog ordinal 순서대로 정렬
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/components/expense/ExpenseDates/ExpenseDates.tsx
  frontend/src/pages/TripsPage/TripsPage.tsx
  frontend/src/stories/trips/TripsItemList.stories.tsx
  frontend/src/types/expense.ts
  frontend/src/utils/sort.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#319 TripsPage Footer 이상하게 보이는 문제 해결
  frontend/src/components/trips/TripsItemList/TripsItemList.style.ts
  frontend/src/components/trips/TripsItemList/TripsItemList.tsx
Labels: 🐞 Bug, 🔨 Refactor, FE

#322 행록 디자인 시스템 버전 업데이트
  frontend/package-lock.json
  frontend/package.json
Labels: 🌏 Environment, FE

#314 Bug Issue에서 environment 필수 입력조건 해제
  .github/ISSUE_TEMPLATE/bug.yml
Labels: 🔨 Refactor

#327 cypress 설치
  frontend/cypress.config.ts
  frontend/cypress/e2e/spec.cy.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/cypress/videos/spec.cy.ts.mp4
  frontend/package-lock.json
  frontend/package.json
  frontend/src/constants/api.ts
  frontend/src/pages/TripsPage/TripsPage.tsx
Labels: 🌏 Environment, FE

#334 info 로그 파일에 request 정보 추가 #333
  backend/src/main/java/filter/RequestLoggingFilter.java
  backend/src/main/java/hanglog/config/RequestLoggingConfig.java
  backend/src/main/resources/info-appender.xml
Labels: 🔨 Refactor, BE

#330 cypress e2e 테스트 자동화 yml 추가
  .github/workflows/frontend-e2e-test.yml
  frontend/cypress.config.ts
  frontend/cypress/e2e/spec.cy.ts
  frontend/cypress/videos/spec.cy.ts.mp4
  frontend/tsconfig.json
Labels: 🌏 Environment, FE

#315 사용자이미지 메뉴 아이템 클릭시 닫는 기능추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/layout/Header/Header.tsx
Labels: 🐞 Bug, FE

#361 별점 이상하게 움직이는 문제 해결
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
Labels: 🔨 Refactor, FE

#256 지도 마커 클릭시, 해당 아이템 리스트 중앙에 위치하는 기능
  frontend/src/components/common/TripItem/TripItem.style.ts
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/components/common/TripItemMarker/TripItemMarker.tsx
  frontend/src/hooks/common/useAutoScroll.ts
  frontend/src/store/scrollFocus.ts
Labels: ✨ Feature, FE

#354 TripEditPage cypress 테스트 코드 추가
  frontend/cypress/e2e/trip.cy.ts
  frontend/cypress/fixtures/trip.json
  frontend/cypress/support/e2e.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/DateInput/DateInput.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/components/trip/TripItemAddModal/TitleInput/TitleInput.tsx
  frontend/src/mocks/data/trip.ts
  frontend/src/mocks/handlers/image.ts
  frontend/src/mocks/handlers/trips.ts
Labels: FE

#363 TripPage & TripEditPage 모바일 대응
  .github/workflows/frontend-e2e-test.yml
  frontend/src/App.tsx
  frontend/src/components/common/DayLogItem/DayLogItemSkeleton.tsx
  frontend/src/components/common/DayLogItem/TitleInput/TitleInput.style.ts
  frontend/src/components/common/DayLogList/DayLogList.style.ts
  frontend/src/components/common/TripInformation/TripInformation.style.ts
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/common/TripItem/EditMenu/EditMenu.style.ts
  frontend/src/components/common/TripItem/EditMenu/EditMenu.tsx
  frontend/src/components/common/TripItem/TripItem.style.ts
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/components/common/TripItem/TripItemSkeleton.tsx
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/components/layout/Footer/Footer.style.ts
  frontend/src/components/layout/Header/Header.style.ts
  frontend/src/components/trip/TripItemAddModal/DateInput/DateInput.style.ts
  frontend/src/components/trip/TripItemAddModal/DateInput/DateInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.style.ts
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/components/trips/TripsItem/TripsItem.style.ts
  frontend/src/constants/ui.ts
  frontend/src/hooks/common/useMediaQuery.ts
  frontend/src/hooks/common/useScrollFocus.ts
  frontend/src/pages/ExpensePage/ExpensePage.tsx
  frontend/src/pages/TripCreatePage/TripCreatePage.tsx
  frontend/src/pages/TripEditPage/TripEditPage.style.ts
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/pages/TripPage/TripPage.style.ts
  frontend/src/pages/TripPage/TripPage.tsx
  frontend/src/store/mediaQuery.ts
  frontend/src/stories/common/DayLogList.stories.tsx
  frontend/src/stories/trip/PlaceInput.stories.tsx
  frontend/src/stories/trips/TripsItemList.stories.tsx
Labels: ✨ Feature, FE

#366 ExpensePage 모바일 대응
  frontend/src/assets/svg/error-image.svg
  frontend/src/components/common/Error/Error.tsx
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.style.ts
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.tsx
  frontend/src/components/expense/ExpenseListSection/ExpenseListSection.style.ts
  frontend/src/components/expense/ExpenseListSection/ExpenseListSection.tsx
  frontend/src/components/expense/ExpenseListSection/ExpenseListSectionSkeleton.tsx
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSection.style.ts
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSection.tsx
  frontend/src/pages/ExpensePage/ExpensePage.style.ts
  frontend/src/pages/ExpensePage/ExpensePage.tsx
  frontend/src/pages/ExpensePage/ExpensePageSkeleton.tsx
  frontend/src/pages/NotFoundPage/NotFoundPage.tsx
Labels: ✨ Feature, FE

#372 통화 select에서 어떤 통화인지 보여주기
  frontend/cypress.config.ts
  frontend/cypress/e2e/trip.cy.ts
  frontend/src/components/trip/TripItemAddModal/ExpenseInput/ExpenseInput.tsx
Labels: 🔨 Refactor, FE

#374 Trips 페이지 모바일 대응 반응형 구현
  frontend/src/assets/svg/tutorial1.svg
  frontend/src/assets/svg/tutorial2.svg
  frontend/src/assets/svg/tutorial3.svg
  frontend/src/assets/svg/tutorial4.svg
  frontend/src/components/trips/TripsHeader/TripsHeader.style.ts
  frontend/src/components/trips/TripsHeader/TripsHeader.tsx
  frontend/src/components/trips/TripsItem/TripsItem.style.ts
  frontend/src/components/trips/TripsItemList/TripsItemList.style.ts
  frontend/src/components/trips/TripsItemList/TripsItemList.tsx
  frontend/src/components/trips/TutorialModal/TutorialModal.style.ts
  frontend/src/components/trips/TutorialModal/TutorialModal.tsx
  frontend/src/pages/TripsPage/TripsPage.style.ts
Labels: ✨ Feature, FE

#362 여행생성 페이지 모바일 대응 반응형 구현
  frontend/src/components/common/CitySearchBar/CitySearchBar.style.ts
  frontend/src/components/common/CitySuggestion/CitySuggestion.style.ts
  frontend/src/components/common/DateInput/DateInput.style.ts
  frontend/src/components/common/DateInput/DateInput.tsx
  frontend/src/components/trip/TripCreateForm/TripCreateForm.style.ts
  frontend/src/pages/TripCreatePage/TripCreatePage.style.ts
  frontend/src/pages/TripCreatePage/TripCreatePage.tsx
Labels: 🔨 Refactor, FE

#378 TripCreatePage cypress 테스트
  frontend/cypress/e2e/createTrip.cy.ts
  frontend/cypress/e2e/spec.cy.ts
Labels: ✨ Feature, FE

#384 tripsPage cypress 자동화 테스트 작성
  frontend/cypress/e2e/trips.cy.ts
  frontend/cypress/fixtures/trips.json
Labels: ✨ Feature, FE

#177 OAuth API 코드 리팩토링
  backend/src/main/java/hanglog/global/exception/AuthException.java
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/main/java/hanglog/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/hanglog/member/controller/OAuthLoginController.java
  backend/src/main/java/hanglog/member/domain/Member.java
  backend/src/main/java/hanglog/member/domain/MemberState.java
  backend/src/main/java/hanglog/member/domain/auth/AccessToken.java
  backend/src/main/java/hanglog/member/domain/auth/Provider.java
  backend/src/main/java/hanglog/member/domain/auth/Providers.java
  backend/src/main/java/hanglog/member/domain/auth/UserInfo.java
  backend/src/main/java/hanglog/member/domain/auth/google/GoogleProvider.java
  backend/src/main/java/hanglog/member/domain/auth/google/GoogleUserInfo.java
  backend/src/main/java/hanglog/member/domain/auth/kakao/KakaoProvider.java
  backend/src/main/java/hanglog/member/domain/auth/kakao/KakaoUserInfo.java
  backend/src/main/java/hanglog/member/domain/repository/MemberRepository.java
  backend/src/main/java/hanglog/member/presentation/OAuthLoginController.java
  backend/src/main/java/hanglog/member/provider/GoogleProperties.java
  backend/src/main/java/hanglog/member/provider/KakaoProperties.java
  backend/src/main/java/hanglog/member/provider/Provider.java
  backend/src/main/java/hanglog/member/provider/ProviderProperties.java
  backend/src/main/java/hanglog/member/service/AuthService.java
  backend/src/main/java/hanglog/member/service/OAuthLoginService.java
  backend/src/main/java/hanglog/member/service/dto/AccessTokenRequestDto.java
  backend/src/main/resources/application.yml
Labels: 🔨 Refactor, BE

#359 기간 update시 dayLog를 순서대로 반환하도록 변경
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: 🐞 Bug, 🔨 Refactor, BE

#388 DayLog 순서 변경 test hotfix #387
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: 🐞 Bug, 🔨 Refactor, BE

#390 MyPage 페이지 구현
  frontend/src/components/myPage/EditUserProfileForm/EditUserProfileForm.style.ts
  frontend/src/components/myPage/EditUserProfileForm/EditUserProfileForm.tsx
  frontend/src/components/myPage/EditUserProfileForm/NicknameInput/NicknameInput.style.ts
  frontend/src/components/myPage/EditUserProfileForm/NicknameInput/NicknameInput.tsx
  frontend/src/components/myPage/EditUserProfileForm/ProfileImageInput/ProfileImageInput.style.ts
  frontend/src/components/myPage/EditUserProfileForm/ProfileImageInput/ProfileImageInput.tsx
  frontend/src/components/trips/TripsItemList/TripsItemListSkeleton.tsx
  frontend/src/constants/path.ts
  frontend/src/constants/ui.ts
  frontend/src/pages/MyPage/MyPage.style.ts
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/stories/myPage/EditUserProfileForm.stories.tsx
  frontend/src/stories/myPage/NicknameInput.stories.tsx
  frontend/src/stories/myPage/ProfileImageInput.stories.tsx
Labels: ✨ Feature, FE

#380 TripInfoEditModal 모바일 반응형 구현
  frontend/src/components/common/CitySearchBar/CitySearchBar.style.ts
  frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
  frontend/src/components/common/DateInput/DateInput.style.ts
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.style.ts
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/pages/TripCreatePage/TripCreatePage.style.ts
Labels: ✨ Feature, FE

#385 feat: daylog 및 카테고리 반환 순서 보장
  backend/src/main/java/hanglog/expense/service/ExpenseService.java
Labels: ✨ Feature, BE

#383 깃허브액션 서브모듈 적용
  .github/workflows/backend-CI-test.yml
  .gitmodules
Labels: 🌏 Environment, BE

#393 Trip 수정 시 image url null 값 허용
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/dto/request/TripUpdateRequest.java
  backend/src/main/java/hanglog/trip/service/TripService.java
Labels: 🔨 Refactor, BE

#400 test data sql 작성
  backend/build.gradle
  backend/src/test/java/hanglog/global/IntegrationTest.java
  backend/src/test/resources/data/categories.sql
  backend/src/test/resources/data/cities.sql
  backend/src/test/resources/data/currency.sql
  backend/src/test/resources/data/integration-data.sql
  backend/src/test/resources/data/truncate.sql
Labels: ✨ Feature, BE

#412 package.json에 repository & contributors 추가
  frontend/package-lock.json
  frontend/package.json
Labels: 🔨 Refactor, FE

#398 페이지전환시 화면 최상단으로 랜더링
  frontend/src/App.tsx
  frontend/src/components/common/ScrollTop/ScrollTop.tsx
Labels: ✨ Feature, FE

#420 스토리북 무한 생성 문제 해결
  frontend/.storybook/preview.tsx
  frontend/src/api/axiosInstance.ts
  frontend/src/constants/api.ts
Labels: 🐞 Bug, FE

#422 ExpensePage 스토리북 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/stories/expense/ExpenseCategories.stories.tsx
  frontend/src/stories/expense/ExpenseCategoryInformation.stories.tsx
  frontend/src/stories/expense/ExpenseDates.stories.tsx
  frontend/src/stories/expense/ExpenseInformation.stories.tsx
  frontend/src/stories/expense/ExpenseItem.stories.tsx
  frontend/src/stories/expense/ExpenseList.stories.tsx
  frontend/src/stories/expense/ExpenseListSection.stories.tsx
  frontend/src/stories/expense/TotalExpenseSection.stories.tsx
Labels: ✨ Feature, FE

#421 일일 환율 조회 스케줄링 추가
  backend/src/main/java/hanglog/HangLogApplication.java
  backend/src/main/java/hanglog/currency/service/CurrencyService.java
  backend/src/main/java/hanglog/global/exception/InvalidCurrencyDateException.java
  backend/src/main/java/hanglog/trip/dto/request/ItemsOrdinalUpdateRequest.java
  backend/src/test/java/hanglog/currency/service/CurrencyServiceTest.java
Labels: ✨ Feature, BE

#429 OAuth RedirectURI 잘못 매핑되는 문제 수정
  frontend/src/constants/api.ts
Labels: FE

#405 공유기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/trip/patchTripShareStatus.ts
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.style.ts
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
  frontend/src/components/common/TripInformation/TripInformation.style.ts
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.style.ts
  frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/api/useTripShareStatusMutation.ts
  frontend/src/hooks/trip/useTripEditForm.ts
  frontend/src/hooks/trip/useTripShare.ts
  frontend/src/mocks/data/trip.ts
  frontend/src/mocks/handlers/trips.ts
  frontend/src/types/trip.ts
Labels: ✨ Feature, FE

#403 비용 타입 변경 및 범위 제한 추가
  .idea/.gitignore
  .idea/2023-hang-log.iml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  backend/src/main/java/hanglog/expense/domain/Amount.java
  backend/src/main/java/hanglog/expense/domain/CategoryExpense.java
  backend/src/main/java/hanglog/expense/domain/DayLogExpense.java
  backend/src/main/java/hanglog/expense/domain/Expense.java
  backend/src/main/java/hanglog/expense/dto/response/CategoryExpenseResponse.java
  backend/src/main/java/hanglog/expense/dto/response/DayLogExpenseResponse.java
  backend/src/main/java/hanglog/expense/dto/response/ItemExpenseResponse.java
  backend/src/main/java/hanglog/expense/dto/response/TripExpenseResponse.java
  backend/src/main/java/hanglog/expense/service/ExpenseService.java
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/dto/request/ExpenseRequest.java
  backend/src/main/java/hanglog/trip/dto/request/ItemRequest.java
  backend/src/main/java/hanglog/trip/dto/request/ItemUpdateRequest.java
  backend/src/main/java/hanglog/trip/presentation/ItemController.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/category/fixture/CategoryFixture.java
  backend/src/test/java/hanglog/currency/service/CurrencyServiceTest.java
  backend/src/test/java/hanglog/expense/fixture/AmountFixture.java
  backend/src/test/java/hanglog/expense/fixture/ExchangeableExpenseFixture.java
  backend/src/test/java/hanglog/expense/fixture/ExpenseFixture.java
  backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
  backend/src/test/java/hanglog/expense/presentation/ExpenseControllerTest.java
  backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
  backend/src/test/java/hanglog/trip/domain/ItemTest.java
  backend/src/test/java/hanglog/trip/fixture/ExpenseFixture.java
  backend/src/test/java/hanglog/trip/presentation/ItemControllerTest.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: 🐞 Bug, BE

#436 인증인가 코드 리팩토링
  frontend/cypress/e2e/trip.cy.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/interceptors.ts
  frontend/src/api/member/putUserInfo.ts
  frontend/src/components/common/LogIn/LogIn.tsx
  frontend/src/components/myPage/EditUserProfileForm/EditUserProfileForm.tsx
  frontend/src/components/myPage/EditUserProfileForm/NicknameInput/NicknameInput.tsx
  frontend/src/components/myPage/EditUserProfileForm/ProfileImageInput/ProfileImageInput.tsx
  frontend/src/components/trip/TripInfoEditModal/ImageInput/ImageInput.tsx
  frontend/src/components/trip/TripItemAddModal/ExpenseInput/ExpenseInput.tsx
  frontend/src/components/trip/TripItemAddModal/ImageInput/ImageInput.tsx
  frontend/src/hooks/common/useImageUpload.ts
  frontend/src/hooks/common/useMultipleImageUpload.ts
  frontend/src/hooks/common/useSingleImageUpload.ts
  frontend/src/hooks/member/useEditUserProfileForm.ts
  frontend/src/hooks/member/useTokenError.ts
  frontend/src/mocks/handlers/trips.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#439 favicon 추가
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/webpack.config.js
Labels: ✨ Feature, FE

#446 로그아웃 API 수정으로 인한 리팩토링
  frontend/src/api/member/deleteLogOut.ts
  frontend/src/api/member/postLogOut.ts
  frontend/src/components/layout/Header/LoggedInMenu/LoggedInMenu.tsx
  frontend/src/hooks/api/useLogOutMutation.ts
  frontend/src/mocks/handlers/member.ts
Labels: 🔨 Refactor, FE

#448 클라이언트 http요청시 https로 리다이렉션 기능 추가
  frontend/src/components/utils/HttpsRedirect.tsx
  frontend/src/constants/regex.ts
  frontend/src/index.tsx
Labels: ✨ Feature, FE

#452 AuthException 로깅 추가
  backend/src/main/java/hanglog/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/hanglog/global/exception/ImageException.java
  backend/src/main/java/hanglog/global/exception/InvalidCurrencyDateException.java
  backend/src/main/java/hanglog/global/exception/InvalidDomainException.java
Labels: 🔨 Refactor, BE

#430 Trip 테스트 및 통합 fixture 추가
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/test/java/hanglog/global/IntegrationFixture.java
  backend/src/test/java/hanglog/global/ServiceIntegrationTest.java
  backend/src/test/java/hanglog/trip/integration/DayLogIntegrationTest.java
  backend/src/test/java/hanglog/trip/integration/TripIntegrationTest.java
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
  backend/src/test/java/hanglog/trip/service/integration/TripServiceIntegrationTest.java
  backend/src/test/resources/data/cities.sql
Labels: 🔨 Refactor, BE

#456 쿠키 addHeader 타입 변경
  backend/src/main/java/hanglog/auth/presentation/AuthController.java
Labels: 🐞 Bug, 🔨 Refactor, BE

#460 공유페이지 구현
  frontend/src/api/trip/getSharedTrip.ts
  frontend/src/components/common/DayLogItem/DayLogItem.tsx
  frontend/src/components/common/DayLogList/DayLogList.tsx
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/constants/api.ts
  frontend/src/hooks/api/useSharedTripQuery.ts
  frontend/src/mocks/handlers/trips.ts
  frontend/src/pages/SharedPage/SharedPage.tsx
  frontend/src/router/AppRouter.tsx
Labels: ✨ Feature, FE

#467 공유 오류 수정
  backend/src/main/java/hanglog/trip/domain/repository/TripRepository.java
Labels: 🐞 Bug, BE

#473 amount 로직 변경
  backend/src/main/java/hanglog/expense/domain/Amount.java
Labels: 🐞 Bug, BE

#475 feat: 토큰 예외처리 상태코드 추가, 예외 시 accessToken 제거 로직 추가
  frontend/src/api/interceptors.ts
  frontend/src/constants/api.ts
Labels: FE

#481 기타 탭에서 장소 추가되는 문제 해결
  frontend/src/components/trip/TripItemAddModal/DateInput/DateInput.tsx
Labels: 🐞 Bug, FE

#478 금액 입력할 때 1 입력 후 안 지워지는 문제 해결
  frontend/src/constants/regex.ts
Labels: 🐞 Bug, FE

#482 트립생성 페이지 스켈레톤 적용
  frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.style.ts
  frontend/src/components/trip/TripCreateForm/TripCreateForm.style.ts
  frontend/src/components/trip/TripCreateForm/TripCreateFormSkeleton.tsx
  frontend/src/pages/TripCreatePage/TripCreatePage.tsx
  frontend/src/router/AppRouter.tsx
Labels: ✨ Feature, FE

#485 총 금액들 소수점 없이 보여주기
  frontend/src/components/expense/ExpenseCategories/ExpenseCategories.tsx
  frontend/src/components/expense/ExpenseDates/ExpenseDates.tsx
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSection.tsx
  frontend/src/mocks/data/expense.ts
Labels: 🔨 Refactor, FE

#487 회원 탈퇴 기능 추가
  frontend/src/api/member/deleteAccount.ts
  frontend/src/components/myPage/EditUserProfileForm/EditUserProfileForm.style.ts
  frontend/src/components/myPage/EditUserProfileForm/EditUserProfileForm.tsx
  frontend/src/constants/api.ts
  frontend/src/hooks/api/useDeleteAccountMutation.ts
  frontend/src/mocks/handlers/member.ts
Labels: ✨ Feature, FE

#493 버그 수정
  frontend/src/components/common/DonutChart/DonutChart.tsx
  frontend/src/components/common/TripItem/TripItem.style.ts
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/components/expense/ExpenseCategoryInformation/ExpenseCategoryInformation.tsx
  frontend/src/components/trip/TripItemAddModal/DateInput/DateInput.tsx
  frontend/src/constants/trip.ts
  frontend/src/constants/ui.ts
Labels: 🐞 Bug, FE

#496 프론트 버그 해결
  frontend/cypress/e2e/trip.cy.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/DayLogItem/DayLogItem.tsx
  frontend/src/components/common/DayLogItem/DayLogItemSkeleton.tsx
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.style.ts
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.tsx
  frontend/src/components/expense/ExpenseItem/ExpenseItem.style.ts
  frontend/src/components/expense/ExpenseItem/ExpenseItem.tsx
Labels: 🐞 Bug, FE

#498 로그인상태에서 로그인,회원가입페이지 접근시 홈으로 리다이렉트
  frontend/src/constants/ui.ts
  frontend/src/pages/LogInPage/LogInPage.tsx
  frontend/src/pages/SignUpPage/SignUpPage.tsx
Labels: 🔨 Refactor, FE

#497 package.json 버전 1.0.0으로 업데이트
  frontend/package-lock.json
  frontend/package.json
Labels: 🌏 Environment, FE

#500 docs: 프로젝트 아키텍쳐 이미지 추가
  README.md
Labels: 🔨 Refactor

#508 마이페이지에서 닉네임 공백 입력되는 버그 수정
  backend/src/main/java/hanglog/member/presentation/MemberController.java
  frontend/src/components/expense/ExpenseCategoryInformation/ExpenseCategoryInformation.tsx
  frontend/src/hooks/member/useEditUserProfileForm.ts
Labels: 🐞 Bug, BE, FE
