Repository woowacourse-teams/2023-hang-log, pull requests merged in 2023-09, with the labels that each got.

#533 ExpensePage 리팩토링
  frontend/cypress/e2e/createTrip.cy.ts
  frontend/src/api/interceptors.ts
  frontend/src/components/expense/ExpenseCategories/ExpenseCategories.tsx
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.tsx
  frontend/src/components/expense/ExpenseItem/ExpenseItem.style.ts
  frontend/src/components/expense/ExpenseItem/ExpenseItem.tsx
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSection.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/ui.ts
  frontend/src/hooks/expense/useExpense.ts
  frontend/src/stories/expense/ExpenseInformation.stories.tsx
Labels: 🔨 Refactor, FE

#537 TripPage, TripEditPage 리팩토링
  frontend/.storybook/preview.tsx
  frontend/cypress/e2e/login.cy.ts
  frontend/cypress/e2e/trip.cy.ts
  frontend/src/assets/svg/bin-icon.svg
  frontend/src/assets/svg/edit-icon.svg
  frontend/src/components/common/DayLogList/DayLogList.tsx
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.style.ts
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
  frontend/src/components/common/TripInformation/TripEditButtons/TripEditButtons.tsx
  frontend/src/components/common/TripInformation/TripInformation.style.ts
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.style.ts
  frontend/src/components/common/TripItem/EditMenu/EditMenu.style.ts
  frontend/src/components/common/TripItem/EditMenu/EditMenu.tsx
  frontend/src/components/common/TripItem/TripItem.style.ts
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/components/layout/Footer/Footer.tsx
  frontend/src/components/layout/Header/Header.style.ts
  frontend/src/components/layout/Header/LoggedInMenu/LoggedInMenu.style.ts
  frontend/src/components/layout/Header/LoggedOutMenu/LoggedOutMenu.tsx
  frontend/src/components/trip/TripItemAddModal/DateInput/DateInput.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/api/useCityQuery.ts
  frontend/src/hooks/api/useExpenseCategoryQuery.ts
  frontend/src/hooks/api/useExpenseQuery.ts
  frontend/src/hooks/api/useImageMutation.ts
  frontend/src/hooks/api/useSharedTripQuery.ts
  frontend/src/hooks/api/useTripEditPageQueries.ts
  frontend/src/hooks/api/useTripQuery.ts
  frontend/src/hooks/api/useTripsQuery.ts
  frontend/src/hooks/api/useUserInfoQuery.ts
  frontend/src/hooks/trip/useAddTripItemForm.ts
  frontend/src/hooks/trip/useTrip.ts
  frontend/src/index.tsx
  frontend/src/pages/IntroPage/IntroPage.tsx
  frontend/src/pages/LogInPage/LogInPage.style.ts
  frontend/src/pages/LogInPage/LogInPage.tsx
  frontend/src/pages/SharedPage/SharedPage.tsx
  frontend/src/pages/SignUpPage/SignUpPage.tsx
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/pages/TripPage/TripPage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/stories/common/TripInformation.stories.tsx
Labels: 🐞 Bug, 🔨 Refactor, FE

#540 삭제 컨펌 경고 모달 추가
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.style.ts
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
  frontend/src/components/common/TripItem/EditMenu/EditMenu.style.ts
  frontend/src/components/common/TripItem/EditMenu/EditMenu.tsx
Labels: 🔨 Refactor, FE

#541 MyPage 리팩토링
  frontend/src/components/myPage/EditUserProfileForm/EditUserProfileForm.style.ts
  frontend/src/components/myPage/EditUserProfileForm/EditUserProfileForm.tsx
Labels: 🔨 Refactor, FE

#531 금액순으로 카테고리 정렬 구현
  backend/src/main/java/hanglog/expense/service/ExpenseService.java
  backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
Labels: ✨ Feature, BE

#546 번들 사이즈 최적화
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/index.d.ts
  frontend/src/assets/jpg/sample-trip-image.jpg
  frontend/src/assets/jpg/sample-trip-image_mobile.jpg
  frontend/src/assets/png/sample-trip-image.png
  frontend/src/assets/png/sample-trip-image_mobile.png
  frontend/src/components/myPage/EditUserProfileForm/EditUserProfileForm.style.ts
  frontend/src/pages/IntroPage/IntroPage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/router/lazy.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: 🔨 Refactor, FE

#549 npm run build 시 오래 걸리는 문제 해결
  frontend/package.json
  frontend/webpack.config.js
Labels: 🐞 Bug, FE

#550 모바일 환경에서 StarRatingInput 호버 문제 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/trip/TripItemAddModal/StarRatingInput/StarRatingInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/stories/trip/StarRatingInput.stories.tsx
Labels: 🔨 Refactor, FE

#544 모바일 버전에서 지도 볼 수 있는 기능
  frontend/src/components/common/DayLogList/DayLogList.style.ts
  frontend/src/pages/TripPage/TripMobilePage.tsx
  frontend/src/pages/TripPage/TripPage.style.ts
  frontend/src/pages/TripPage/TripPage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/router/lazy.ts
  frontend/webpack.config.js
Labels: ✨ Feature, FE

#557 토글버튼 부활, UI관련 수정
  frontend/src/components/common/DayLogItem/DayLogItem.tsx
  frontend/src/components/common/DayLogItem/DayLogItemSkeleton.tsx
  frontend/src/components/common/GoogleMapWrapper/GoogleMapWrapper.tsx
  frontend/src/components/common/TripInformation/TripInformation.style.ts
  frontend/src/components/common/TripItem/TripItem.style.ts
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/ui.ts
  frontend/src/hooks/api/queryClient.ts
  frontend/src/hooks/trip/useResizeImage.ts
  frontend/src/index.tsx
Labels: 🔨 Refactor, FE

#556 sharedtrip 변경사항 flyway script 작성
  backend/src/main/resources/db/migration/V2__Add_base_entity_to_shared_trip.sql
Labels: ✨ Feature, BE

#529 refactor: TripCity 삭제 로직 추가
  backend/src/main/java/hanglog/trip/service/TripService.java
Labels: 🔨 Refactor, BE

#563 테스트코드 패키지 변경
  backend/src/test/java/hanglog/auth/presentation/AuthControllerTest.java
  backend/src/test/java/hanglog/category/presentation/CategoryControllerTest.java
  backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
  backend/src/test/java/hanglog/expense/presentation/ExpenseControllerTest.java
  backend/src/test/java/hanglog/global/ControllerTest.java
  backend/src/test/java/hanglog/global/restdocs/RestDocsConfiguration.java
  backend/src/test/java/hanglog/image/presentation/ImageControllerTest.java
  backend/src/test/java/hanglog/integration/IntegrationFixture.java
  backend/src/test/java/hanglog/integration/controller/DayLogIntegrationTest.java
  backend/src/test/java/hanglog/integration/controller/IntegrationTest.java
  backend/src/test/java/hanglog/integration/controller/ItemIntegrationTest.java
  backend/src/test/java/hanglog/integration/controller/SharedTripIntegrationTest.java
  backend/src/test/java/hanglog/integration/controller/TripIntegrationTest.java
  backend/src/test/java/hanglog/integration/service/AuthServiceIntegrationTest.java
  backend/src/test/java/hanglog/integration/service/ServiceIntegrationTest.java
  backend/src/test/java/hanglog/integration/service/TripServiceIntegrationTest.java
  backend/src/test/java/hanglog/member/controller/MemberControllerTest.java
  backend/src/test/java/hanglog/share/fixture/ShareFixture.java
  backend/src/test/java/hanglog/share/presentation/SharedTripControllerTest.java
  backend/src/test/java/hanglog/trip/fixture/DayLogFixture.java
  backend/src/test/java/hanglog/trip/fixture/TripFixture.java
  backend/src/test/java/hanglog/trip/presentation/DayLogControllerTest.java
  backend/src/test/java/hanglog/trip/presentation/ItemControllerTest.java
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: 🔨 Refactor, BE

#560 webpack 최적화 및 common, prod, dev 파일 분리
  .github/workflows/frontend-e2e-test.yml
  frontend/config/webpack.common.js
  frontend/config/webpack.dev.js
  frontend/config/webpack.prod.js
  frontend/config/webpackUtil.js
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.config.js
Labels: 🔨 Refactor, FE

#565 닉네임 랜덤 숫자 추가 및 수정 시 닉네임 중복 체크
  backend/src/main/java/hanglog/auth/service/AuthService.java
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/main/java/hanglog/member/domain/Member.java
  backend/src/main/java/hanglog/member/domain/repository/MemberRepository.java
  backend/src/main/java/hanglog/member/service/MemberService.java
  backend/src/main/resources/db/migration/V3__Add_unique_to_member_nickname.sql
Labels: ✨ Feature, BE

#569 Trip, Like, PublishedTrip 테이블 생성
  backend/src/main/java/hanglog/trip/domain/Like.java
  backend/src/main/java/hanglog/trip/domain/PublishedTrip.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/domain/type/PublishedStatusType.java
  backend/src/main/resources/db/migration/V4__Creat_table_published_trip_and_like.sql
  backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
  backend/src/test/java/hanglog/share/fixture/ShareFixture.java
  backend/src/test/java/hanglog/trip/fixture/DayLogFixture.java
  backend/src/test/java/hanglog/trip/fixture/TripFixture.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: ✨ Feature, BE

#570 이미지 압축
  frontend/.prettierrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/constants/image.ts
  frontend/src/hooks/common/useMultipleImageUpload.ts
  frontend/src/hooks/common/useSingleImageUpload.ts
Labels: ✨ Feature, FE

#576 마이페이지 수정 시 닉네임 변경되지 않은 경우 예외 발생 버그 해결
  backend/src/main/java/hanglog/member/domain/Member.java
  backend/src/main/java/hanglog/member/presentation/MemberController.java
  backend/src/main/java/hanglog/member/service/MemberService.java
Labels: 🐞 Bug, BE

#580 여행 아이템 사진 확대해서 볼 수 있는 기능 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/TripItem/TripItem.style.ts
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/hooks/common/useMediaQuery.ts
  frontend/src/hooks/trip/useExpandImage.ts
  frontend/src/hooks/trip/useResizeImage.ts
  frontend/src/store/mediaQuery.ts
Labels: ✨ Feature, FE

#586 성능 최적화 - 사용자 이미지 아이콘 width, height 추가
  frontend/config/webpack.prod.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/layout/Header/LoggedInMenu/LoggedInMenu.style.ts
Labels: 🔨 Refactor, FE

#559 경비 공유 페이지 생성
  frontend/src/api/expense/getSharedExpense.ts
  frontend/src/api/trip/getSharedTrip.ts
  frontend/src/components/common/DayLogItem/DayLogItem.style.ts
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
  frontend/src/components/common/TripInformation/TripInformation.style.ts
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
  frontend/src/components/common/TripMap/TripMap.tsx
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.tsx
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSection.tsx
  frontend/src/components/trip/TripCreateForm/TripCreateForm.style.ts
  frontend/src/components/trip/TripInfoEditModal/ImageInput/ImageInput.tsx
  frontend/src/components/trips/TripsItem/TripsItem.style.ts
  frontend/src/components/trips/TripsItem/TripsItem.tsx
  frontend/src/components/trips/TutorialModal/TutorialModal.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/api/useExpenseQuery.ts
  frontend/src/hooks/api/useLogInMutation.ts
  frontend/src/mocks/handlers/expense.ts
  frontend/src/mocks/handlers/trips.ts
  frontend/src/pages/ExpensePage/ExpensePage.tsx
  frontend/src/pages/SharedPage/SharedTripPage.tsx
  frontend/src/pages/TripPage/TripMobilePage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/router/lazy.ts
  frontend/src/stories/expense/ExpenseInformation.stories.tsx
  frontend/src/stories/expense/TotalExpenseSection.stories.tsx
Labels: ✨ Feature, FE

#588 S3, CloudFront 배포로 인한 api 주소 변경
  frontend/src/constants/api.ts
Labels: 🐞 Bug, FE

#594 dev서버에서 백서버로 api요청 안가는 오류 해결 ->axios base url환경변수 변경
  frontend/src/constants/api.ts
Labels: 🐞 Bug, 🌏 Environment, FE

#595 공유된 여행 가계부 조회 기능 추가
  backend/src/docs/asciidoc/docs.adoc
  backend/src/main/java/hanglog/share/presentation/SharedTripController.java
  backend/src/test/java/hanglog/expense/presentation/ExpenseControllerTest.java
  backend/src/test/java/hanglog/share/presentation/SharedTripControllerTest.java
Labels: ✨ Feature, BE

#591 SharedCode index 설정 추가
  backend/src/main/java/hanglog/share/domain/SharedTrip.java
  backend/src/main/resources/db/migration/V5__Add_index_to_shared_trip.sql
Labels: 🔨 Refactor, BE

#597 이미지 저장 시 cache-control 메타데이터 추가
  backend/src/main/java/hanglog/image/service/ImageService.java
Labels: ✨ Feature, BE

#603 cors 추가 설정
  backend/src/main/java/hanglog/global/config/CorsConfig.java
Labels: 🔨 Refactor, BE

#612 allowCredentials True로 설정
  backend/src/main/java/hanglog/global/config/CorsConfig.java
Labels: 🐞 Bug, 🔨 Refactor, BE

#613 refactor: allowCredentials True로 설정
  backend/src/main/java/hanglog/global/config/CorsConfig.java
Labels: 🐞 Bug, 🔨 Refactor, BE

#592 여행 공개 상태 변경 API 구현
  backend/src/docs/asciidoc/docs.adoc
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/main/java/hanglog/trip/domain/PublishedTrip.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/domain/repository/PublishedTripRepository.java
  backend/src/main/java/hanglog/trip/domain/type/PublishedStatusType.java
  backend/src/main/java/hanglog/trip/dto/request/PublishedStatusRequest.java
  backend/src/main/java/hanglog/trip/presentation/TripController.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: ✨ Feature, BE

#587 커뮤니티 여행 조회 페이지네이션 기능 구현
  backend/src/docs/asciidoc/docs.adoc
  backend/src/main/java/hanglog/community/domain/Likes.java
  backend/src/main/java/hanglog/community/domain/PublishedTrip.java
  backend/src/main/java/hanglog/community/domain/repository/LikesRepository.java
  backend/src/main/java/hanglog/community/domain/type/PublishedStatusType.java
  backend/src/main/java/hanglog/community/dto/response/CommunityTripListResponse.java
  backend/src/main/java/hanglog/community/dto/response/CommunityTripResponse.java
  backend/src/main/java/hanglog/community/presentation/CommunityController.java
  backend/src/main/java/hanglog/community/service/CommunityService.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/domain/repository/PublishedTripRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/TripRepository.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/main/resources/db/migration/V7__Rename_table_like_to_likes.sql
  backend/src/test/java/hanglog/community/presentation/CommunityControllerTest.java
  backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
  backend/src/test/java/hanglog/share/fixture/ShareFixture.java
  backend/src/test/java/hanglog/trip/fixture/DayLogFixture.java
  backend/src/test/java/hanglog/trip/fixture/TripFixture.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: ✨ Feature, BE

#616 Drop 권한 거절로 인한 db 마이그레이션 스크립트 변경
  backend/src/main/resources/db/migration/V4__Creat_table_published_trip_and_like.sql
  backend/src/main/resources/db/migration/V7__Rename_table_like_to_likes.sql
Labels: 🔨 Refactor, BE

#619 tripId 프롭스, 파라미터 타입 전부 string으로 수정
  frontend/src/api/dayLog/patchDayLogItemOrder.ts
  frontend/src/api/dayLog/patchDayLogTitle.ts
  frontend/src/api/expense/getExpense.ts
  frontend/src/api/trip/deleteTrip.ts
  frontend/src/api/trip/getTrip.ts
  frontend/src/api/trip/patchTripShareStatus.ts
  frontend/src/api/trip/putTrip.ts
  frontend/src/api/tripItem/deleteTripItem.ts
  frontend/src/api/tripItem/postTripItem.ts
  frontend/src/api/tripItem/putTripItem.ts
  frontend/src/components/common/DayLogItem/DayLogItem.tsx
  frontend/src/components/common/DayLogItem/TitleInput/TitleInput.tsx
  frontend/src/components/common/DayLogList/DayLogList.tsx
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
  frontend/src/components/common/TripInformation/TripEditButtons/TripEditButtons.tsx
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
  frontend/src/components/common/TripItem/EditMenu/EditMenu.tsx
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/components/common/TripItemList/TripItemList.tsx
  frontend/src/components/expense/ExpenseCategories/ExpenseCategories.tsx
  frontend/src/components/expense/ExpenseCategoryInformation/ExpenseCategoryInformation.tsx
  frontend/src/components/expense/ExpenseDates/ExpenseDates.tsx
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.tsx
  frontend/src/components/expense/ExpenseList/ExpenseList.tsx
  frontend/src/components/expense/ExpenseListSection/ExpenseListSection.tsx
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSection.tsx
  frontend/src/components/trip/TripItemAddModal/DateInput/DateInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/api/useExpenseQuery.ts
  frontend/src/hooks/api/useLogInMutation.ts
  frontend/src/hooks/api/useSharedTripQuery.ts
  frontend/src/hooks/api/useTripEditPageQueries.ts
  frontend/src/hooks/api/useTripQuery.ts
  frontend/src/hooks/expense/useExpense.ts
  frontend/src/hooks/trip/useAddTripItemForm.ts
  frontend/src/hooks/trip/useTrip.ts
  frontend/src/hooks/trip/useTripEditForm.ts
  frontend/src/pages/ExpensePage/ExpensePage.tsx
  frontend/src/pages/SharedPage/SharedTripPage.tsx
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/pages/TripPage/TripMobilePage.tsx
  frontend/src/pages/TripPage/TripPage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/stories/common/DayLogItem.stories.tsx
  frontend/src/stories/common/DayLogList.stories.tsx
  frontend/src/stories/common/TripInformation.stories.tsx
  frontend/src/stories/common/TripItem.stories.tsx
  frontend/src/stories/common/TripItemList.stories.tsx
  frontend/src/stories/expense/ExpenseCategories.stories.tsx
  frontend/src/stories/expense/ExpenseCategoryInformation.stories.tsx
  frontend/src/stories/expense/ExpenseDates.stories.tsx
  frontend/src/stories/expense/ExpenseInformation.stories.tsx
  frontend/src/stories/expense/ExpenseList.stories.tsx
  frontend/src/stories/expense/ExpenseListSection.stories.tsx
  frontend/src/stories/expense/TotalExpenseSection.stories.tsx
  frontend/src/stories/trip/DateInput.stories.tsx
  frontend/src/stories/trip/TripItemAddModal.stories.tsx
Labels: 🔨 Refactor, FE

#617 커뮤니티 여행 추천 목록 조회 API 구현
  backend/src/docs/asciidoc/docs.adoc
  backend/src/main/java/hanglog/community/domain/recommendstrategy/LikesRecommendStrategy.java
  backend/src/main/java/hanglog/community/domain/recommendstrategy/RecommendStrategies.java
  backend/src/main/java/hanglog/community/domain/recommendstrategy/RecommendStrategy.java
  backend/src/main/java/hanglog/community/domain/recommendstrategy/RecommendType.java
  backend/src/main/java/hanglog/community/dto/response/CommunityTripResponse.java
  backend/src/main/java/hanglog/community/dto/response/RecommendTripListResponse.java
  backend/src/main/java/hanglog/community/presentation/CommunityController.java
  backend/src/main/java/hanglog/community/service/CommunityService.java
  backend/src/main/java/hanglog/global/exception/ExceptionCode.java
  backend/src/main/java/hanglog/trip/domain/repository/TripRepository.java
  backend/src/test/java/hanglog/community/presentation/CommunityControllerTest.java
Labels: ✨ Feature, BE

#625 fix:경비공유페이지 버그 수정 => 잘못된 id전달로 인한 오류
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSection.tsx
  frontend/src/pages/ExpensePage/ExpensePage.tsx
Labels: 🐞 Bug, FE

#636 커뮤니티 좋아요 API 구현
  backend/src/docs/asciidoc/docs.adoc
  backend/src/main/java/hanglog/community/domain/Likes.java
  backend/src/main/java/hanglog/community/domain/PublishedTrip.java
  backend/src/main/java/hanglog/community/domain/repository/LikeRepository.java
  backend/src/main/java/hanglog/community/domain/repository/LikesRepository.java
  backend/src/main/java/hanglog/community/dto/request/LikeRequest.java
  backend/src/main/java/hanglog/community/presentation/LikeController.java
  backend/src/main/java/hanglog/community/service/CommunityService.java
  backend/src/main/java/hanglog/community/service/LikeService.java
  backend/src/main/java/hanglog/trip/domain/repository/TripRepository.java
  backend/src/main/resources/db/migration/V7__Add_unique_to_trip_id_and_member_id.sql
  backend/src/test/java/hanglog/community/presentation/LikeControllerTest.java
  backend/src/test/java/hanglog/integration/service/LikeServiceIntegrationTest.java
  backend/src/test/java/hanglog/trip/presentation/ItemControllerTest.java
Labels: ✨ Feature, BE

#639 Shared Status 이동
  backend/src/main/java/hanglog/share/domain/SharedTrip.java
  backend/src/main/java/hanglog/share/dto/response/SharedTripCodeResponse.java
  backend/src/main/java/hanglog/share/service/SharedTripService.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/resources/db/migration/V8__Move_shared_status_to_trip.sql
  backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
  backend/src/test/java/hanglog/share/fixture/ShareFixture.java
  backend/src/test/java/hanglog/share/presentation/SharedTripControllerTest.java
  backend/src/test/java/hanglog/share/service/SharedTripServiceTest.java
  backend/src/test/java/hanglog/trip/fixture/DayLogFixture.java
  backend/src/test/java/hanglog/trip/fixture/TripFixture.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: 🔨 Refactor, BE

#640 커뮤니티 페이지 조회 및 경비 조회 구현
  backend/src/docs/asciidoc/docs.adoc
  backend/src/main/java/hanglog/community/domain/BaseTripInfo.java
  backend/src/main/java/hanglog/community/domain/TripInfo.java
  backend/src/main/java/hanglog/community/domain/repository/LikeRepository.java
  backend/src/main/java/hanglog/community/dto/response/CommunityTripDetailResponse.java
  backend/src/main/java/hanglog/community/presentation/CommunityController.java
  backend/src/main/java/hanglog/community/service/CommunityService.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/domain/repository/PublishedTripRepository.java
  backend/src/test/java/hanglog/community/presentation/CommunityControllerTest.java
  backend/src/test/java/hanglog/integration/service/CommunityServiceIntegrationTest.java
Labels: ✨ Feature, BE

#644 Like 테이블 존재시 tripInfo null값 반영 해결
  backend/src/main/java/hanglog/community/domain/repository/LikeRepository.java
  backend/src/main/java/hanglog/community/dto/response/CommunityTripDetailResponse.java
  backend/src/main/java/hanglog/community/service/CommunityService.java
  backend/src/test/java/hanglog/community/presentation/CommunityControllerTest.java
Labels: 🐞 Bug, BE
