Repository woowacourse-teams/2023-hang-log, pull requests merged in 2023-10, with the labels that each got.

#648 커뮤니티에서 로그인 에러나는 버그정
  frontend/src/api/trip/getCommunityTrip.ts
  frontend/src/components/common/LikeButton/LikeButton.tsx
  frontend/src/components/community/CommunityHeader/CommunityHeader.tsx
  frontend/src/components/trips/CommunityTripItemList/CommunityTripItemList.tsx
  frontend/src/components/trips/CommunityTripsItem/CommunityTripsItem.tsx
  frontend/src/components/trips/TripsHeader/TripsHeader.style.ts
  frontend/src/hooks/api/useCommunityTripQuery.ts
  frontend/src/hooks/api/useTripQuery.ts
  frontend/src/mocks/data/communityTripsData.ts
  frontend/src/mocks/data/recommendedTripsData.ts
  frontend/src/pages/CommunityPage/CommunityPage.tsx
  frontend/src/types/trips.ts
Labels: 🐞 Bug, FE

#656 PageNavigation Index 5 미만 시 발생하는 레이아웃 문제, 쿠키 없을 경우 발생하는 인증인가 문제 해결
  frontend/src/api/interceptors.ts
  frontend/src/hooks/common/usePageIndex.ts
  frontend/src/pages/CommunityPage/CommunityPage.tsx
Labels: 🔨 Refactor, FE

#660 단일 여행 조회 Dto 통합
  backend/src/main/java/hanglog/community/dto/response/CommunityTripDetailResponse.java
  backend/src/main/java/hanglog/community/presentation/CommunityController.java
  backend/src/main/java/hanglog/community/service/CommunityService.java
  backend/src/main/java/hanglog/share/dto/response/SharedTripDetailResponse.java
  backend/src/main/java/hanglog/share/presentation/SharedTripController.java
  backend/src/main/java/hanglog/share/service/SharedTripService.java
  backend/src/main/java/hanglog/trip/dto/response/TripDetailResponse.java
  backend/src/main/java/hanglog/trip/dto/response/type/TripType.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/test/java/hanglog/community/presentation/CommunityControllerTest.java
  backend/src/test/java/hanglog/integration/controller/TripIntegrationTest.java
  backend/src/test/java/hanglog/integration/service/CommunityServiceIntegrationTest.java
  backend/src/test/java/hanglog/integration/service/TripServiceIntegrationTest.java
  backend/src/test/java/hanglog/share/presentation/SharedTripControllerTest.java
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: 🔨 Refactor, BE

#665 DayLog 수정 모달에서 이미지 여러 번에 걸쳐 넣을 때 발생하는 문제 수정
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/hooks/common/useMultipleImageUpload.ts
Labels: 🔨 Refactor, FE

#664 캐싱 문제, 토큰 문제 해결
  frontend/src/api/interceptors.ts
  frontend/src/hooks/api/useCommunityTripQuery.ts
  frontend/src/hooks/api/useLikeMutation.ts
  frontend/src/hooks/api/useRecommendedTripsQuery.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#654 Google Analytics script 추가
  frontend/public/index.html
Labels: ✨ Feature, FE

#667 UX개선 : 사진 업로드 시간이 길어질 때, 사용자가 이미지 업로드 완료 여부를 파악하기 힘든 문제 개선
  frontend/src/components/myPage/EditUserProfileForm/EditUserProfileForm.style.ts
  frontend/src/components/myPage/EditUserProfileForm/EditUserProfileForm.tsx
  frontend/src/components/myPage/EditUserProfileForm/ProfileImageInput/ProfileImageInput.style.ts
  frontend/src/components/myPage/EditUserProfileForm/ProfileImageInput/ProfileImageInput.tsx
  frontend/src/components/trip/TripItemAddModal/ImageInput/ImageInput.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/hooks/api/useCommunityTripQuery.ts
  frontend/src/hooks/api/useTripQuery.ts
  frontend/src/hooks/api/useUpdateTripItemMutation.ts
  frontend/src/hooks/common/useMultipleImageUpload.ts
  frontend/src/hooks/common/useSingleImageUpload.ts
  frontend/src/mocks/handlers/image.ts
  frontend/src/pages/TripPage/TripMobilePage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/stories/myPage/ProfileImageInput.stories.tsx
Labels: ✨ Feature, FE

#671 대표이미지 업로드 안되는 버그 수정
  frontend/src/hooks/api/useTripQuery.ts
  frontend/src/hooks/api/useTripShareStatusMutation.ts
  frontend/src/hooks/common/useMultipleImageUpload.ts
  frontend/src/hooks/trip/useTripEditForm.ts
Labels: 🐞 Bug, FE

#670 refactor: 로그아웃 로직 변경
  backend/src/main/java/hanglog/auth/domain/repository/RefreshTokenRepository.java
  backend/src/main/java/hanglog/auth/presentation/AuthController.java
  backend/src/main/java/hanglog/auth/service/AuthService.java
  backend/src/test/java/hanglog/auth/presentation/AuthControllerTest.java
Labels: 🔨 Refactor, BE

#673 메인페이지 하트, 이름 높낮이 문제 수정 + queryClient 캐시 수정
  frontend/src/components/trips/CommunityTripsItem/CommunityTripsItem.tsx
  frontend/src/hooks/api/queryClient.ts
Labels: 🔨 Refactor, FE

#678 데이로그 아이템 사진 별개로 한개 추가시, 그 사진만 등록되는 버그수정
  frontend/src/components/trip/TripInfoEditModal/ImageInput/ImageInput.tsx
  frontend/src/hooks/common/useMultipleImageUpload.ts
Labels: 🐞 Bug, FE

#680 accessToken 재발급 요청에서 발생하는 오류 세분화 - develop
  backend/src/main/java/hanglog/auth/domain/JwtProvider.java
  backend/src/main/java/hanglog/auth/service/AuthService.java
Labels: 🐞 Bug, 🔨 Refactor, BE

#679 accessToken 재발급 요청에서 발생하는 오류 세분화 - main
  backend/src/main/java/hanglog/auth/domain/JwtProvider.java
  backend/src/main/java/hanglog/auth/service/AuthService.java
Labels: 🐞 Bug, BE

#677 데이로그 아이템 사진 별개로 한개 추가시, 그 사진만 등록되는 버그수정
  frontend/src/components/trip/TripInfoEditModal/ImageInput/ImageInput.tsx
  frontend/src/hooks/common/useMultipleImageUpload.ts
Labels: 🐞 Bug, FE

#651 여행 생성 및 여행 상세 조회 쿼리 개선
  backend/src/main/java/hanglog/city/domain/repository/CityRepository.java
  backend/src/main/java/hanglog/expense/dto/response/TripExpenseResponse.java
  backend/src/main/java/hanglog/global/filter/RequestLoggingFilter.java
  backend/src/main/java/hanglog/trip/domain/DayLog.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/domain/repository/CustomDayLogRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/CustomDayLogRepositoryImpl.java
  backend/src/main/java/hanglog/trip/domain/repository/CustomTripCityRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/CustomTripCityRepositoryImpl.java
  backend/src/main/java/hanglog/trip/domain/repository/TripRepository.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
  backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
  backend/src/test/java/hanglog/integration/IntegrationFixture.java
  backend/src/test/java/hanglog/integration/service/CommunityServiceIntegrationTest.java
  backend/src/test/java/hanglog/integration/service/LikeServiceIntegrationTest.java
  backend/src/test/java/hanglog/integration/service/TripServiceIntegrationTest.java
  backend/src/test/java/hanglog/share/fixture/ShareFixture.java
  backend/src/test/java/hanglog/trip/fixture/DayLogFixture.java
  backend/src/test/java/hanglog/trip/fixture/ItemFixture.java
  backend/src/test/java/hanglog/trip/service/DayLogServiceTest.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: 🔨 Refactor, BE

#683 메인페이지 텍스트 줄바꿈문제, 여백 문제 수정 - main
  frontend/src/components/trips/TripsHeader/TripsHeader.style.ts
  frontend/src/pages/CommunityPage/CommunityPage.style.ts
Labels: 🔨 Refactor, FE

#572 Query Counter (aka. N+1 Detector) 를 통한 API별 쿼리 정보 정리
  backend/src/main/java/hanglog/global/detector/ConnectionProxyHandler.java
  backend/src/main/java/hanglog/global/detector/LoggingForm.java
  backend/src/main/java/hanglog/global/detector/PreparedStatementProxyHandler.java
  backend/src/main/java/hanglog/global/detector/QueryCounterAop.java
  backend/src/main/resources/info-appender.xml
Labels: 🙋 Suggestion, ✨ Feature, BE

#685 UI 변경사항 적용
  frontend/cypress/e2e/trip.cy.ts
  frontend/cypress/fixtures/recommendedTrips.json
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/expense/ExpenseCategories/ExpenseCategories.tsx
  frontend/src/components/expense/ExpenseCategoryInformation/ExpenseCategoryInformation.tsx
  frontend/src/components/expense/ExpenseDates/ExpenseDates.tsx
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.tsx
  frontend/src/components/expense/ExpenseListSection/ExpenseListSection.tsx
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSection.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/trip/TripInfoEditModal/ImageInput/ImageInput.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.style.ts
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.style.ts
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/components/trips/CommunityTripsItem/CommunityTripsItem.style.ts
  frontend/src/components/trips/CommunityTripsItem/CommunityTripsItem.tsx
  frontend/src/components/trips/TripsHeader/TripsHeader.style.ts
  frontend/src/components/trips/TripsItem/TripsItem.style.ts
  frontend/src/hooks/api/useCityQuery.ts
  frontend/src/hooks/api/useCommunityTripQuery.ts
  frontend/src/hooks/api/useExpenseQuery.ts
  frontend/src/hooks/api/useRecommendedTripsQuery.ts
  frontend/src/hooks/api/useTripEditMutation.ts
  frontend/src/hooks/api/useTripQuery.ts
  frontend/src/hooks/api/useUserInfoQuery.ts
  frontend/src/hooks/expense/useExpense.ts
  frontend/src/mocks/data/recommendedTripsData.ts
  frontend/src/pages/CommunityTripPage/CommunityTripPage.tsx
  frontend/src/pages/ExpensePage/ExpensePage.tsx
  frontend/src/pages/SharedPage/SharedTripPage.tsx
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/pages/TripPage/TripMobilePage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/stories/expense/ExpenseCategories.stories.tsx
  frontend/src/stories/expense/ExpenseCategoryInformation.stories.tsx
  frontend/src/stories/expense/ExpenseDates.stories.tsx
  frontend/src/stories/expense/ExpenseInformation.stories.tsx
  frontend/src/stories/expense/ExpenseListSection.stories.tsx
  frontend/src/stories/expense/TotalExpenseSection.stories.tsx
Labels: 🔨 Refactor, FE

#691 빌드 속도 개선을 위한 ts-loader -> esbuild-loader 마이그레이션
  frontend/config/webpack.common.js
  frontend/package-lock.json
  frontend/package.json
Labels: 🌏 Environment, 🔨 Refactor, FE

#687 Member 탈퇴에 따른 엔티티 Soft Delete 처리 성능 개선
  backend/src/main/java/hanglog/HangLogApplication.java
  backend/src/main/java/hanglog/auth/domain/repository/RefreshTokenRepository.java
  backend/src/main/java/hanglog/auth/service/AuthService.java
  backend/src/main/java/hanglog/community/dto/response/CommunityTripResponse.java
  backend/src/main/java/hanglog/community/service/CommunityService.java
  backend/src/main/java/hanglog/expense/domain/repository/ExpenseRepository.java
  backend/src/main/java/hanglog/expense/service/ExpenseService.java
  backend/src/main/java/hanglog/image/domain/repository/ImageRepository.java
  backend/src/main/java/hanglog/listener/MemberDeleteEventListener.java
  backend/src/main/java/hanglog/member/domain/MemberDeleteEvent.java
  backend/src/main/java/hanglog/member/domain/repository/MemberRepository.java
  backend/src/main/java/hanglog/member/dto/response/WriterResponse.java
  backend/src/main/java/hanglog/share/domain/repository/SharedTripRepository.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/domain/repository/CustomDayLogRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/CustomItemRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/CustomTripRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/DayLogRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/ItemRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/PlaceRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/PublishedTripRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/TripRepository.java
  backend/src/main/java/hanglog/trip/domain/type/PublishedStatusType.java
  backend/src/main/java/hanglog/trip/domain/type/SharedStatusType.java
  backend/src/main/java/hanglog/trip/dto/ItemElement.java
  backend/src/main/java/hanglog/trip/dto/response/TripDetailResponse.java
  backend/src/main/java/hanglog/trip/infrastructure/CustomDayLogRepositoryImpl.java
  backend/src/main/java/hanglog/trip/infrastructure/CustomItemRepositoryImpl.java
  backend/src/main/java/hanglog/trip/infrastructure/CustomTripCityRepositoryImpl.java
  backend/src/main/java/hanglog/trip/infrastructure/CustomTripRepositoryImpl.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
  backend/src/test/java/hanglog/integration/service/AuthServiceIntegrationTest.java
  backend/src/test/java/hanglog/integration/service/CommunityServiceIntegrationTest.java
  backend/src/test/java/hanglog/integration/service/LikeServiceIntegrationTest.java
  backend/src/test/java/hanglog/integration/service/TripServiceIntegrationTest.java
  backend/src/test/java/hanglog/member/event/MemberDeleteEventListenerTest.java
  backend/src/test/java/hanglog/share/fixture/ShareFixture.java
  backend/src/test/java/hanglog/trip/fixture/DayLogFixture.java
  backend/src/test/java/hanglog/trip/fixture/TripFixture.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: 🔨 Refactor, BE

#701 UI 변경사항 적용
  frontend/cypress/e2e/trip.cy.ts
  frontend/cypress/fixtures/recommendedTrips.json
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/expense/ExpenseCategories/ExpenseCategories.tsx
  frontend/src/components/expense/ExpenseCategoryInformation/ExpenseCategoryInformation.tsx
  frontend/src/components/expense/ExpenseDates/ExpenseDates.tsx
  frontend/src/components/expense/ExpenseInformation/ExpenseInformation.tsx
  frontend/src/components/expense/ExpenseListSection/ExpenseListSection.tsx
  frontend/src/components/expense/TotalExpenseSection/TotalExpenseSection.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/trip/TripInfoEditModal/ImageInput/ImageInput.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.style.ts
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.style.ts
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/components/trips/CommunityTripsItem/CommunityTripsItem.style.ts
  frontend/src/components/trips/CommunityTripsItem/CommunityTripsItem.tsx
  frontend/src/components/trips/TripsHeader/TripsHeader.style.ts
  frontend/src/components/trips/TripsItem/TripsItem.style.ts
  frontend/src/hooks/api/useCityQuery.ts
  frontend/src/hooks/api/useCommunityTripQuery.ts
  frontend/src/hooks/api/useExpenseQuery.ts
  frontend/src/hooks/api/useRecommendedTripsQuery.ts
  frontend/src/hooks/api/useTripEditMutation.ts
  frontend/src/hooks/api/useTripQuery.ts
  frontend/src/hooks/api/useUserInfoQuery.ts
  frontend/src/hooks/expense/useExpense.ts
  frontend/src/mocks/data/recommendedTripsData.ts
  frontend/src/pages/CommunityTripPage/CommunityTripPage.tsx
  frontend/src/pages/ExpensePage/ExpensePage.tsx
  frontend/src/pages/SharedPage/SharedTripPage.tsx
  frontend/src/pages/TripEditPage/TripEditPage.tsx
  frontend/src/pages/TripPage/TripMobilePage.tsx
  frontend/src/router/AppRouter.tsx
  frontend/src/stories/expense/ExpenseCategories.stories.tsx
  frontend/src/stories/expense/ExpenseCategoryInformation.stories.tsx
  frontend/src/stories/expense/ExpenseDates.stories.tsx
  frontend/src/stories/expense/ExpenseInformation.stories.tsx
  frontend/src/stories/expense/ExpenseListSection.stories.tsx
  frontend/src/stories/expense/TotalExpenseSection.stories.tsx
Labels: 🐞 Bug, 🔨 Refactor

#703 ts-loader -> esbuild-loader 마이그레이션
  backend/src/main/java/hanglog/global/detector/ConnectionProxyHandler.java
  backend/src/main/java/hanglog/global/detector/LoggingForm.java
  backend/src/main/java/hanglog/global/detector/PreparedStatementProxyHandler.java
  backend/src/main/java/hanglog/global/detector/QueryCounterAop.java
  backend/src/main/resources/info-appender.xml
  frontend/config/webpack.common.js
  frontend/package-lock.json
  frontend/package.json
Labels: 🔨 Refactor

#697 백엔드 이미지 로직 수정에 의한 코드 리팩토링
  frontend/cypress/e2e/trip.cy.ts
  frontend/cypress/fixtures/communityTrips.json
  frontend/cypress/fixtures/recommendedTrips.json
  frontend/cypress/fixtures/trip.json
  frontend/cypress/fixtures/trips.json
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/common/TripItem/EditMenu/EditMenu.tsx
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/components/myPage/EditUserProfileForm/EditUserProfileForm.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/components/trips/CommunityTripsItem/CommunityTripsItem.tsx
  frontend/src/components/trips/TripsItem/TripsItem.tsx
  frontend/src/components/trips/TripsItemList/TripsItemList.tsx
  frontend/src/hooks/api/useTripShareStatusMutation.ts
  frontend/src/hooks/common/useMultipleImageUpload.ts
  frontend/src/hooks/common/useSingleImageUpload.ts
  frontend/src/hooks/trip/useAddTripItemForm.ts
  frontend/src/hooks/trip/useTripEditForm.ts
  frontend/src/mocks/data/communityTrip.ts
  frontend/src/mocks/data/communityTripsData.ts
  frontend/src/mocks/data/myTrips.ts
  frontend/src/mocks/data/recommendedTripsData.ts
  frontend/src/mocks/data/sharedTrip.ts
  frontend/src/mocks/data/trip.ts
  frontend/src/mocks/handlers/image.ts
  frontend/src/mocks/handlers/myTrips.ts
  frontend/src/mocks/handlers/tripItem.ts
  frontend/src/stories/trip/TripItemAddModal.stories.tsx
  frontend/src/stories/trips/TripsItem.stories.tsx
  frontend/src/types/image.ts
  frontend/src/types/trip.ts
  frontend/src/types/tripItem.ts
  frontend/src/types/trips.ts
  frontend/src/utils/convertImageName.ts
  frontend/src/utils/convertImageNames.ts
Labels: 🔨 Refactor, FE

#708 단일 여행, 아이템 삭제 쿼리 개선
  backend/src/main/java/hanglog/expense/domain/repository/ExpenseRepository.java
  backend/src/main/java/hanglog/image/domain/repository/ImageRepository.java
  backend/src/main/java/hanglog/listener/DeleteEventListener.java
  backend/src/main/java/hanglog/share/domain/repository/SharedTripRepository.java
  backend/src/main/java/hanglog/trip/domain/TripDeleteEvent.java
  backend/src/main/java/hanglog/trip/domain/repository/CustomDayLogRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/ItemRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/PlaceRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/PublishedTripRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/TripCityRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/TripRepository.java
  backend/src/main/java/hanglog/trip/infrastructure/CustomDayLogRepositoryImpl.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/test/java/hanglog/member/event/DeleteEventListenerTest.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: 🔨 Refactor, BE

#709 커뮤니티 전체&추천 여행 목록 조회 쿼리 개선
  backend/src/main/java/hanglog/community/domain/BaseTripInfo.java
  backend/src/main/java/hanglog/community/domain/LikeInfo.java
  backend/src/main/java/hanglog/community/domain/TripInfo.java
  backend/src/main/java/hanglog/community/domain/repository/LikeRepository.java
  backend/src/main/java/hanglog/community/dto/CityElement.java
  backend/src/main/java/hanglog/community/dto/CityElements.java
  backend/src/main/java/hanglog/community/dto/LikeElement.java
  backend/src/main/java/hanglog/community/dto/LikeElements.java
  backend/src/main/java/hanglog/community/presentation/CommunityController.java
  backend/src/main/java/hanglog/community/service/CommunityService.java
  backend/src/main/java/hanglog/trip/domain/repository/TripCityRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/TripRepository.java
  backend/src/test/java/hanglog/community/presentation/CommunityControllerTest.java
  backend/src/test/java/hanglog/integration/service/CommunityServiceIntegrationTest.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: 🔨 Refactor, BE

#710 아이템 수정 & 데이로그 수정 & 아이템 oridinal 수정 재업로드
  backend/src/main/java/hanglog/category/domain/Category.java
  backend/src/main/java/hanglog/expense/domain/Expense.java
  backend/src/main/java/hanglog/image/domain/Image.java
  backend/src/main/java/hanglog/image/domain/repository/CustomImageRepository.java
  backend/src/main/java/hanglog/image/infrastructure/CustomImageRepositoryImpl.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/domain/Place.java
  backend/src/main/java/hanglog/trip/domain/repository/CustomItemRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/DayLogRepository.java
  backend/src/main/java/hanglog/trip/infrastructure/CustomItemRepositoryImpl.java
  backend/src/main/java/hanglog/trip/service/DayLogService.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/integration/controller/ItemIntegrationTest.java
  backend/src/test/java/hanglog/trip/service/DayLogServiceTest.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: 🔨 Refactor, BE

#711 단일 여행 조회 및 경비 조회 api 개선
  backend/src/main/java/hanglog/category/domain/ExpenseCategories.java
  backend/src/main/java/hanglog/community/service/CommunityService.java
  backend/src/main/java/hanglog/currency/domain/OldestCurrency.java
  backend/src/main/java/hanglog/expense/dto/response/TripExpenseResponse.java
  backend/src/main/java/hanglog/expense/service/ExpenseService.java
  backend/src/main/java/hanglog/share/domain/repository/SharedTripRepository.java
  backend/src/main/java/hanglog/share/service/SharedTripService.java
  backend/src/main/java/hanglog/trip/domain/repository/TripRepository.java
  backend/src/test/java/hanglog/community/presentation/CommunityControllerTest.java
  backend/src/test/java/hanglog/expense/presentation/ExpenseControllerTest.java
  backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
  backend/src/test/java/hanglog/share/presentation/SharedTripControllerTest.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: 🔨 Refactor, BE

#714 스프링 이벤트를 사용한 S3 이미지 파일 삭제 기능 추가
  backend/src/main/java/hanglog/image/domain/S3ImageEvent.java
  backend/src/main/java/hanglog/image/infrastructure/ImageUploader.java
  backend/src/main/java/hanglog/image/service/ImageService.java
  backend/src/main/java/hanglog/listener/DeleteEventListener.java
  backend/src/main/java/hanglog/listener/S3ImageEventListener.java
  backend/src/main/java/hanglog/member/service/MemberService.java
  backend/src/main/java/hanglog/trip/domain/Trip.java
  backend/src/main/java/hanglog/trip/dto/request/TripUpdateRequest.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/main/java/hanglog/trip/service/TripService.java
  backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
  backend/src/test/java/hanglog/trip/service/TripServiceTest.java
Labels: ✨ Feature, BE

#715 대표이미지 수정버그, 아이템 이미지 등록삭제시 생기는 버그 수정
  frontend/src/components/common/TripInformation/TripInformation.tsx
  frontend/src/components/common/TripItem/TripItem.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.style.ts
  frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
  frontend/src/components/trips/CommunityTripsItem/CommunityTripsItem.tsx
  frontend/src/components/trips/TripsItem/TripsItem.tsx
  frontend/src/hooks/api/useImageMutation.ts
  frontend/src/hooks/common/useMultipleImageUpload.ts
  frontend/src/hooks/trip/useAddTripItemForm.ts
  frontend/src/mocks/data/image.ts
  frontend/src/mocks/handlers/tripItem.ts
  frontend/src/utils/convertImage.ts
  frontend/src/utils/convertImageName.ts
  frontend/src/utils/convertImageNames.ts
Labels: 🐞 Bug, 🔨 Refactor, FE

#723 패키지 의존성 분리: 이미지
  backend/src/main/java/hanglog/listener/DeleteEventListener.java
  backend/src/main/java/hanglog/trip/domain/Image.java
  backend/src/main/java/hanglog/trip/domain/Item.java
  backend/src/main/java/hanglog/trip/domain/repository/CustomImageRepository.java
  backend/src/main/java/hanglog/trip/domain/repository/ImageRepository.java
  backend/src/main/java/hanglog/trip/dto/response/ImagesResponse.java
  backend/src/main/java/hanglog/trip/dto/response/ItemResponse.java
  backend/src/main/java/hanglog/trip/infrastructure/CustomImageRepositoryImpl.java
  backend/src/main/java/hanglog/trip/presentation/ImageController.java
  backend/src/main/java/hanglog/trip/service/ImageService.java
  backend/src/main/java/hanglog/trip/service/ItemService.java
  backend/src/test/java/hanglog/integration/IntegrationFixture.java
  backend/src/test/java/hanglog/member/event/DeleteEventListenerTest.java
  backend/src/test/java/hanglog/trip/presentation/ImageControllerTest.java
  backend/src/test/java/hanglog/trip/service/ImageServiceTest.java
  backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
Labels: 🔨 Refactor, BE

#721 이미지 업로드 수정
  backend/src/main/java/hanglog/trip/service/ImageService.java
Labels: 🔨 Refactor, BE

#730 refactor: trip 정렬 기준 수정, 하트 svg 수정, 여행 삭제 후 redirect 경로 수정
  frontend/src/assets/svg/empty-like.svg
  frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
  frontend/src/utils/sort.ts
Labels: 🔨 Refactor, FE

#732 이미지 관련 버그(여행대표이미지, 사용자이미지)수정
  frontend/src/components/myPage/EditUserProfileForm/EditUserProfileForm.tsx
  frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
  frontend/src/constants/api.ts
  frontend/src/hooks/api/useUserInfoMutation.ts
  frontend/src/hooks/common/useMultipleImageUpload.ts
  frontend/src/hooks/common/useSingleImageUpload.ts
  frontend/src/hooks/trip/useTripEditForm.ts
Labels: 🐞 Bug, FE

#733 커뮤니티 하트 svg 수정, 최신순정렬 수정
  frontend/src/api/interceptors.ts
  frontend/src/assets/svg/empty-like.svg
  frontend/src/pages/MyTripsPage/MyTripsPage.tsx
  frontend/src/utils/sort.ts
Labels: 🔨 Refactor, FE
